### ISSUE TITLE
go/ir: update for Go 1.17

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#1045]
See also:

 *  mvdan/unparam#55
 *  golang/go#46987

Synopsis:

```none
$ go install honnef.co/go/tools/cmd/staticcheck@master

$ staticcheck --debug.version
  staticcheck (devel, v0.3.0-0.dev.0.20210610122209-28f373ac6cb1)

  Compiled with Go version: go1.17beta1
  Main module:
  	honnef.co/go/tools@v0.3.0-0.dev.0.20210610122209-28f373ac6cb1 (sum: h1:dDPeZNwwZtnwRhE06NPArs32iPjZcu1dERBqcymcSwg=)
  Dependencies:
  	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
  	golang.org/x/mod@v0.4.2 (sum: h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=)
  	golang.org/x/sys@v0.0.0-20210510120138-977fb7262007 (sum: h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=)
  	golang.org/x/tools@v0.1.3-0.20210529002143-6123e5fbf24b (sum: h1:oRWktbvlCLroCQeAn0bO+yyQy8vmj7Fu+J41xJTt1YM=)
  	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)

$ more ./main.go 
  package main

  import (
  	"fmt"
  )

  func main() {
  	fmt.Println(*(*[2]int)([]int{1, 2}))
  }

$ staticcheck ./main.go 
  panic: in command-line-arguments.main: cannot convert Load <[]int> t0 ([]int) to *[2]int

  goroutine 154 [running]:
  honnef.co/go/tools/go/ir.emitConv(0xc000165b00, {0x96ce48, 0xc000293920}, {0x95dd98, 0xc0005b1830}, {0x95d500, 0xc0006083c0})
  	/home/ainar/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20210610122209-28f373ac6cb1/go/ir/emit.go:250 +0x9d4
  honnef.co/go/tools/go/ir.(*builder).expr0(0xc000683b00, 0xc000165b00, {0x95f068, 0xc0006083c0}, {0x7, {0x95dd98, 0xc0005b1830}, {0x0, 0x0}})
  	/home/ainar/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20210610122209-28f373ac6cb1/go/ir/builder.go:544 +0xa77
  […]
```

I guess the vendored version of `golang.org/x/tools` needs updating?

**Comment by dominikh** [comment]
We have a forked and modified version of go/ssa. We'll have to backport the change.

**Comment by dominikh** [comment]
This may also require updating some of our checks. Before this language change, type conversions could not fail at runtime, but now they can.

**Comment by dominikh** [comment]
We should make sure that we support the new functions in `unsafe`, too, while we're here.

**Comment by dominikh** [comment]
I think we're done.

**Comment by ainar-g** [comment]
I confirm that the latest `master` fixes the issue for me.

**Comment by ainar-g** [comment]
@dominikh, should the solution be updated considering the discussion in golang/go#46978 and [CL 333749]?

[CL 333749]: https://go-review.googlesource.com/c/tools/+/333749

**Comment by dominikh** [comment]
@ainar-g Yes, I'll backport that change.

**Comment by ainar-g** [comment]
@dominikh, another one to consider: golang/go#48281.
