### ISSUE TITLE
panic in nilness check 

### ISSUE THREAD

**Issue by kevinburkemeter** [dominikh/go-tools#1069]
Running staticcheck at commit 740f570319eacbf8098b259fd4770779905be852:

```
$ staticcheck -debug.version
staticcheck (no version)

Compiled with Go version: go1.17
Main module:
	honnef.co/go/tools
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/mod@v0.4.2 (sum: h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=)
	golang.org/x/sys@v0.0.0-20210510120138-977fb7262007 (sum: h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=)
	golang.org/x/tools@v0.1.3-0.20210529002143-6123e5fbf24b (sum: h1:oRWktbvlCLroCQeAn0bO+yyQy8vmj7Fu+J41xJTt1YM=)
	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
```

I'm using go 1.17 to compile, but I could also reproduce on Go 1.18 tip. 

I am running

```
GOFLAGS="-mod=vendor -race" GO111MODULE=on staticcheck ./...
```

I see the following panic: 

```
panic: runtime error: index out of range [1] with length 1

goroutine 549 [running]:
honnef.co/go/tools/analysis/facts/nilness.impl.func1({0x15688e8, 0xc0011f6900})
	/Users/kevin/src/honnef.co/go/tools/analysis/facts/nilness/nilness.go:153 +0xddb
honnef.co/go/tools/analysis/facts/nilness.impl.func1({0x1568fd0, 0xc00035d7a0})
	/Users/kevin/src/honnef.co/go/tools/analysis/facts/nilness/nilness.go:140 +0xe7f
honnef.co/go/tools/analysis/facts/nilness.impl(0xc000fd2000, 0xc0016067e0, 0xc001350e48)
	/Users/kevin/src/honnef.co/go/tools/analysis/facts/nilness/nilness.go:232 +0x397
honnef.co/go/tools/analysis/facts/nilness.run(0xc000fd2000)
	/Users/kevin/src/honnef.co/go/tools/analysis/facts/nilness/nilness.go:66 +0x126
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0xc0026f4150, {0x1563278, 0xc0013e1860})
	/Users/kevin/src/honnef.co/go/tools/lintcmd/runner/runner.go:937 +0x614
honnef.co/go/tools/lintcmd/runner.genericHandle({0x1563278, 0xc0013e1860}, {0x1563278, 0xc0013e15e0}, 0x8080104, 0x0, 0xc0013511b8)
	/Users/kevin/src/honnef.co/go/tools/lintcmd/runner/runner.go:762 +0x102
honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers(0xc00007fc70, 0xc000429d40, 0xc000d92be0)
	/Users/kevin/src/honnef.co/go/tools/lintcmd/runner/runner.go:1007 +0x786
honnef.co/go/tools/lintcmd/runner.(*subrunner).doUncached(0x0, 0xc000429d40)
	/Users/kevin/src/honnef.co/go/tools/lintcmd/runner/runner.go:666 +0x1a9
honnef.co/go/tools/lintcmd/runner.(*subrunner).do(0xc00007fc70, {0x15632c0, 0xc000429d40})
	/Users/kevin/src/honnef.co/go/tools/lintcmd/runner/runner.go:529 +0x6e8
honnef.co/go/tools/lintcmd/runner.(*Runner).Run.func2({0x15632c0, 0xc000429d40})
	/Users/kevin/src/honnef.co/go/tools/lintcmd/runner/runner.go:1183 +0x30
honnef.co/go/tools/lintcmd/runner.genericHandle({0x15632c0, 0xc000429d40}, {0x15632c0, 0xc00020f0e0}, 0x0, 0xc0002c00b8, 0xc001fed110)
	/Users/kevin/src/honnef.co/go/tools/lintcmd/runner/runner.go:762 +0x102
created by honnef.co/go/tools/lintcmd/runner.(*Runner).Run
	/Users/kevin/src/honnef.co/go/tools/lintcmd/runner/runner.go:1182 +0x4d4
Command exited with non-zero status 2
6.50user 1.66system 0:02.77elapsed 294%CPU (0avgtext+0avgdata 187676maxresident)k
0inputs+0outputs (6major+93629minor)pagefaults 0swaps
make: *** [Makefile:91: lint] Error 2
```

It's a large closed source project, I suppose I could try to bisect the package list to find out exactly where the error is occurring.

**Comment by kevinburkemeter** [comment]
I didn't observe this error on any of the 1.17 betas or release candidates, which we've been running for several months.

**Comment by kevinburkemeter** [comment]
I'm able to reproduce on this test case. 

```
package blah

import "net/http"

func Foo() *http.Request {
	return nil
}
```

**Comment by kevinburkemeter** [comment]
I tried to bisect to a specific staticcheck commit but I'm getting this other panic if I try even 2021.1

```
panic: in crypto/sha512.Sum384: cannot convert Slice <[]byte> t0 <nil> <nil> <nil> ([]byte) to *[48]byte
```

**Comment by kevinburkemeter** [comment]
I can't reproduce in our Linux test environment, which is odd; I'm not sure if it's Linux or if it's something about beta1.

```
staticcheck 2021.1 (v0.2.0)

Compiled with Go version: go1.17beta1
Main module:
	honnef.co/go/tools@v0.2.0
Dependencies:
	github.com/BurntSushi/toml@v0.3.1
	golang.org/x/mod@v0.4.2
	golang.org/x/sys@v0.0.0-20210510120138-977fb7262007
	golang.org/x/tools@v0.1.6-0.20210715133541-6e9046bfcd34
	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1
```

**Comment by kevinburkemeter** [comment]
Okay, if I run staticcheck with GOROOT set to a `go1.16` source tree I'm able to get it to compile.

**Comment by dominikh** [comment]
> I tried to bisect to a specific staticcheck commit but I'm getting this other panic if I try even 2021.1

Older releases of Staticcheck may not work with Go 1.17 because Go 1.17 introduced the slice to array-pointer conversion. Any code using that will fail to be checked.

> I'm able to reproduce on this test case.

I can't reproduce it with Staticcheck 2021.1.1 on Go 1.17 on Linux.  I _can_ reproduce it with Staticcheck 2021.1.1 on go version devel go1.18-cf12b0d1f9 on Linux. Looking into it.

**Comment by kevinburkemeter** [comment]
> I can reproduce it with Staticcheck 2021.1.1 on go version devel go1.18-cf12b0d1f9 on Linux. Looking into it.

Yeah that makes sense it I think - it depends more on what's in GOROOT when you actually invoke staticcheck than what GOROOT is set to when you compile it, and I had GOROOT set to Go tip for most of these experiments.

**Comment by dominikh** [comment]
That's why the issue template asks for the output of `go env` and `go version` ;)

**Comment by dominikh** [comment]
This is caused by https://github.com/golang/go/issues/44195 – this may take a bit to fix as we have to work with upstream. At this time I can only recommend against running Staticcheck with Go tip.

**Comment by kevinburkemeter** [comment]
> That's why the issue template asks for the output of go env and go version ;)

Right that instruction wouldn't have caught it either I guess, because I was using Go 1.17 to compile staticcheck and assuming that was good enough to test whether the issue reproduced with Go 1.17, when the actual issue was that I needed to set GOROOT=/path/to/go1.17 when I was _running_ staticcheck.

**Comment by dominikh** [comment]
Note that you don't want to set GOROOT, but instead make sure that the correct `go` binary is on your PATH. Staticcheck shells out to `go`. Mismatched versions of Go and GOROOT can cause other problems. Assuming you've done that, the output of `go version` would've then told us that even though Staticcheck was compiled with Go 1.17, it was invoking Go tip.

**Comment by kevinburkemeter** [comment]
> Staticcheck shells out to go.

Ahhhh, this is the part that I was missing... would it make sense to add the go version to the debug output? That would also be a hint that it's important

**Comment by dominikh** [comment]
That's a good idea. #901 tracks it.
