### ISSUE TITLE
cmd/unused: panic: unexpected Object type: builtin unsafe.Alignof

### ISSUE THREAD

**Issue by davecheney** [dominikh/go-tools#107]
```
zapf(~/src/github.com/golang/dep/internal/gps) % unused
panic: unexpected Object type: builtin unsafe.Alignof

goroutine 1 [running]:
honnef.co/go/ssa.memberFromObject(0xc4228e2ae0, 0x146cfe0, 0xc4200773b0, 0x0, 0x0)
        /Users/dfc/src/honnef.co/go/ssa/create.go:103 +0x41f
honnef.co/go/ssa.(*Program).CreatePackage(0xc4223d7ea0, 0xc4200763c0, 0x0, 0x0, 0x0, 0x0, 0xc42a851601, 0x473d6818)
        /Users/dfc/src/honnef.co/go/ssa/create.go:196 +0x7f4
honnef.co/go/lint.buildPackage.func1(0xc42140bb60, 0x1, 0x1)
        /Users/dfc/src/honnef.co/go/lint/lint.go:99 +0x12f
honnef.co/go/lint.buildPackage.func1(0xc42482ea60, 0x3, 0x4)
        /Users/dfc/src/honnef.co/go/lint/lint.go:100 +0x15b
honnef.co/go/lint.buildPackage.func1(0xc42464f040, 0x8, 0x8)
        /Users/dfc/src/honnef.co/go/lint/lint.go:100 +0x15b
honnef.co/go/lint.buildPackage.func1(0xc428ff8200, 0x28, 0x40)
        /Users/dfc/src/honnef.co/go/lint/lint.go:100 +0x15b
honnef.co/go/lint.buildPackage(0xc42019a140, 0xc42515d200, 0x37, 0x40, 0xc4201040f0, 0xc4200cc700, 0x40, 0xc4200d0140)
        /Users/dfc/src/honnef.co/go/lint/lint.go:104 +0x303
honnef.co/go/lint.(*Linter).Lint(0xc4228e4030, 0xc4200cc740, 0x7)
        /Users/dfc/src/honnef.co/go/lint/lint.go:134 +0x1ad
honnef.co/go/lint/lintutil.(*runner).lint(0xc4200ce280, 0xc4200cc740, 0x0)
        /Users/dfc/src/honnef.co/go/lint/lintutil/util.go:166 +0x95
honnef.co/go/lint/lintutil.ProcessArgs(0x12f95ee, 0x6, 0x14681e0, 0xc4200d6160, 0xc4200ce230, 0x5, 0x5)
        /Users/dfc/src/honnef.co/go/lint/lintutil/util.go:148 +0xb2b
main.main()
        /Users/dfc/src/honnef.co/go/unused/cmd/unused/main.go:95 +0x36c
```

**Comment by davecheney** [comment]
This error happens with 
```
go version devel +266a3b6 Wed May 10 01:47:54 2017 +0000 darwin/amd64
```
Compiling unused with Go 1.8.x does not panic.

**Comment by dominikh** [comment]
Please use `honnef.co/go/tools/cmd/unused` instead of `honnef.co/go/unused/cmd/unused`. This bug has been fixed several months ago.
