### ISSUE TITLE
staticcheck panics under lint:file-ignore U1000 pragma

### ISSUE THREAD

**Issue by ohir** [dominikh/go-tools#1073]
### staticcheck panics under lint:file-ignore U1000 pragma

- if   there is `lint:file-ignore U1000`, 
- and  there is a type alias to struct with unexported field in the linted file,
- then staticcheck panics. 

On the same project it does not panic without file-ignore U1000.

```
go version go1.17 darwin/amd64
# go is 1.17 is from official installer
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"

% staticcheck -debug.version
staticcheck 2021.1.1 (v0.2.1)

Compiled with Go version: go1.17
Main module:
	honnef.co/go/tools@v0.2.1 (sum: h1:/EPr//+UMMXwMTkXvCCoaJDq8cpjMO80Ou+L4PDo2mY=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
	golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
	golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)

Tested also with previous tagged version:
staticcheck 2021.1 (v0.2.0)

Compiled with Go version: go1.17
Main module:
        honnef.co/go/tools@v0.2.0 (sum: h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
        golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
        golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
        golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
panic: failed assertion
 ```

MVR code and log attached below. 
There are two variants of panic logged: longer and shorter (both attached)

```
--- go.mod -------------------------------------------------------
go 1.16

module mydomain.com/exrtos

--- test.go ------------------------------------------------------
//NOlint:file-ignore U1000 Ignore report
package exrtos

import "mydomain.com/exrtos/gdnfo"

type rdln = gdnfo.Bcx

type RbLink struct{}

func (r RbLink) Pah() (gdl rdln) { return }

--- gdnfo/mvr.go  ------------------------------------------------
package gdnfo

type Bcx struct { bl uint32 }

```

```
go version go1.17 darwin/amd64

% cd exrtos
exrtos/ % go vet && go build && echo OK
OK

exrtos/ % staticcheck . && echo OK
OK

exrtos/ % sed -i -e '1,1s/NOlint/lint/' test.go

exrtos/ % staticcheck .
panic: failed assertion

---
exrtos/ % staticcheck .
panic: failed assertion

goroutine 116 [running]:
honnef.co/go/tools/unused.assert(...)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/unused/unused.go:150
honnef.co/go/tools/unused.(*graph).use(0xc000329560, {0x1499120, 0xc0004da190}, {0x0, 0x0}, 0x80000000000)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/unused/unused.go:818 +0x2eb
honnef.co/go/tools/unused.(*graph).entry(0xc000329560, 0xc000198280)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/unused/unused.go:1216 +0x1049
honnef.co/go/tools/unused.run(0xc0003611e0)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/unused/unused.go:523 +0x2d2
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0xc000588b40, {0x1562c18, 0xc000582820})
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/lintcmd/runner/runner.go:937 +0x614
honnef.co/go/tools/lintcmd/runner.genericHandle({0x1562c18, 0xc000582820}, {0x1562c18, 0xc0004ce140}, 0x8000102, 0x0, 0xc0001351b8)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/lintcmd/runner/runner.go:762 +0x102
honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers(0xc0004da000, 0xc000488ea0, 0xc0004da2d0)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/lintcmd/runner/runner.go:1007 +0x786
honnef.co/go/tools/lintcmd/runner.(*subrunner).doUncached(0x0, 0xc000488ea0)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/lintcmd/runner/runner.go:666 +0x1a9
honnef.co/go/tools/lintcmd/runner.(*subrunner).do(0xc0004da000, {0x1562c60, 0xc000488ea0})
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/lintcmd/runner/runner.go:529 +0x6e8
honnef.co/go/tools/lintcmd/runner.(*Runner).Run.func2({0x1562c60, 0xc000488ea0})
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/lintcmd/runner/runner.go:1183 +0x30
honnef.co/go/tools/lintcmd/runner.genericHandle({0x1562c60, 0xc000488ea0}, {0x1562c60, 0xc000488d80}, 0xc00004a7d0, 0xc0002fe0b8, 0xc000492750)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/lintcmd/runner/runner.go:762 +0x102
created by honnef.co/go/tools/lintcmd/runner.(*Runner).Run
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/lintcmd/runner/runner.go:1182 +0x4d4

---
exrtos/ % staticcheck .
panic: failed assertion

goroutine 195 [running]:
honnef.co/go/tools/unused.assert(...)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/unused/unused.go:150
honnef.co/go/tools/unused.(*graph).use(0xc0003823c0, {0x1499120, 0xc00055c190}, {0x0, 0x0}, 0x80000000000)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/unused/unused.go:818 +0x2eb
honnef.co/go/tools/unused.(*graph).entry(0xc0003823c0, 0xc0000dc780)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/unused/unused.go:1216 +0x1049
honnef.co/go/tools/unused.run(0xc0003a85b0)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/unused/unused.go:523 +0x2d2
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0xc00060ab40, {0x1562c18, 0xc000550dc0})
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/lintcmd/runner/runner.go:937 +0x614
honnef.co/go/tools/lintcmd/runner.genericHandle({0x1562c18, 0xc000550dc0}, {0x1562c18, 0xc000550140}, 0x0, 0xc0003a40b8, 0xc00061c920)
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/lintcmd/runner/runner.go:762 +0x102
created by honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers
	/userhome/src/pkg/mod/honnef.co/go/tools@v0.2.1/lintcmd/runner/runner.go:1003 +0x725
```

**Comment by dominikh** [comment]
Shorter reproducer:

```
package foo

import "bytes"

//lint:ignore U1000 huh
type foo = bytes.Buffer
```

**Comment by dominikh** [comment]
Fixed. Thanks for your concise example, it made tracking down the bug a lot easier.
