### ISSUE TITLE
nil pointer dereference in quickfix.CheckDeMorgan

### ISSUE THREAD

**Issue by tux21b** [dominikh/go-tools#1133]
Running the ``quickfix.CheckDeMorgan`` check causes a segmentation fault because of a nil pointer dereference. The bug affects staticcheck 0.2.1, 0.2.2 and tip (2020.1-355-ge8e72d0). Earlier version were not tested. The bug also happens in a more complicated Bazel / NoGo setup (that's why the linter is called in the first place). Unfortunately we are not able to ignore any lint errors if the tool itself panics. So a fix is welcome.

The code that triggers the SEGV is https://gitlab.com/cznic/libc, which is a conversion of the C code of libmusl, so do not expect any idiomatic Go code here. The problematic code seems to be ``libc/musl_linux_amd64.go:1552:5``:

```
if !(__isspace(tls, AssignInt32(&c, func() int32 {
	if (*FILE)(unsafe.Pointer((f))).rpos != (*FILE)(unsafe.Pointer((f))).shend {
		return int32(*(*uint8)(unsafe.Pointer(PostIncUintptr(&(*FILE)(unsafe.Pointer(f)).rpos, 1))))
	}
	return X__shgetc(tls, f)
}())) != 0) {
	goto __3
}
```

The error itself happens somewhere in go/printer while printing the AST, but is caused by an AST generated by the CheckDeMorgan rule. Here is the full stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x50ca9b]

goroutine 161 [running]:
go/ast.(*CallExpr).Pos(0x4000000000000000)
        /usr/lib/go/src/go/ast/ast.go:484 +0x1b
go/printer.(*printer).exprList(0xc00c905848, 0xc00c9055e0, {0xc00c988100, 0x2, 0x4}, 0xc0000290c0, 0x1, 0xe0cd, 0x0)
        /usr/lib/go/src/go/printer/nodes.go:198 +0x7e8
go/printer.(*printer).expr1(0xc00c905848, {0x96b3f0, 0xc00bdcc740}, 0x0, 0x1)
        /usr/lib/go/src/go/printer/nodes.go:949 +0x1890
go/printer.(*printer).expr(...)
        /usr/lib/go/src/go/printer/nodes.go:1117
go/printer.(*printer).printNode(0xc00c905848, {0x853440, 0xc00bdcc740})
        /usr/lib/go/src/go/printer/printer.go:1138 +0x375
go/printer.(*Config).fprint(0xc00c905a28, {0x960ca0, 0xc00c996000}, 0x17b5ce8, {0x853440, 0xc00bdcc740}, 0xc00c987f50)
        /usr/lib/go/src/go/printer/printer.go:1319 +0x17c
go/printer.(*printer).nodeSize(0xc00c9066c0, {0x969880, 0xc00bdcc740}, 0xf4240)
        /usr/lib/go/src/go/printer/nodes.go:1720 +0x134
go/printer.(*printer).exprList(0xc00c9066c0, 0xc00c905f40, {0xc00c9880a0, 0x2, 0x0}, 0x2000000000000000, 0x1, 0xc00c905ee8, 0x0)
        /usr/lib/go/src/go/printer/nodes.go:213 +0x8c5
go/printer.(*printer).expr1(0xc00c9066c0, {0x96b3f0, 0xc00bdcc700}, 0x3, 0x2)
        /usr/lib/go/src/go/printer/nodes.go:949 +0x1890
go/printer.(*printer).binaryExpr(0xc00c9066c0, 0xc00c9878c0, 0x1, 0x6, 0x1)
        /usr/lib/go/src/go/printer/nodes.go:751 +0x1a5
go/printer.(*printer).expr1(0xc00c9066c0, {0x96b360, 0xc00c9878c0}, 0x0, 0x1)
        /usr/lib/go/src/go/printer/nodes.go:795 +0x13f6
go/printer.(*printer).expr0(...)
        /usr/lib/go/src/go/printer/nodes.go:1112
go/printer.(*printer).expr1(0xc00c9066c0, {0x96b8a0, 0xc00c9882c0}, 0x0, 0x1)
        /usr/lib/go/src/go/printer/nodes.go:853 +0xa0a
go/printer.(*printer).expr(...)
        /usr/lib/go/src/go/printer/nodes.go:1117
go/printer.(*printer).printNode(0xc00c9066c0, {0x854140, 0xc00c9882c0})
        /usr/lib/go/src/go/printer/printer.go:1138 +0x375
go/printer.(*Config).fprint(0xbcdd00, {0x960ca0, 0xc00c987f20}, 0x7f3384bf8eb8, {0x854140, 0xc00c9882c0}, 0xc00c987f50)
        /usr/lib/go/src/go/printer/printer.go:1319 +0x17c
go/printer.(*Config).Fprint(...)
        /usr/lib/go/src/go/printer/printer.go:1381
go/format.Node({0x960ca0, 0xc00c987f20}, 0x40e887, {0x854140, 0xc00c9882c0})
        /usr/lib/go/src/go/format/format.go:91 +0x326
honnef.co/go/tools/analysis/report.Render(0xc00133a4e0, {0x854140, 0xc00c9882c0})
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/analysis/report/report.go:197 +0x5a
honnef.co/go/tools/quickfix.CheckDeMorgan.func2({0x969fd8, 0xc001b549e0}, {0xc00c574000, 0x6, 0xc00c906e10})
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/quickfix/lint.go:179 +0x3aa
honnef.co/go/tools/analysis/code.PreorderStack.func1({0x969fd8, 0xc001b549e0}, 0x0, {0xc00c574000, 0xc00c569f20, 0x0})
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/analysis/code/visit.go:22 +0x3a
golang.org/x/tools/go/ast/inspector.(*Inspector).WithStack(0xc0021ae030, {0xc005348ea0, 0xc05ca0, 0x20}, 0xc00c906e48)
        /home/christoph/go/pkg/mod/golang.org/x/tools@v0.1.0/go/ast/inspector/inspector.go:126 +0x19a
honnef.co/go/tools/analysis/code.PreorderStack(0x20, 0x7f33d3517a68, {0xc005348ea0, 0x1, 0x1})
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/analysis/code/visit.go:20 +0x8a
honnef.co/go/tools/quickfix.CheckDeMorgan(0x8442e0)
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/quickfix/lint.go:208 +0x8b
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0xc0026332c0, {0x973898, 0xc000625400})
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/lintcmd/runner/runner.go:937 +0x614
honnef.co/go/tools/lintcmd/runner.genericHandle({0x973898, 0xc000625400}, {0x973898, 0xc0000dc1e0}, 0x80d0101, 0x0, 0xc0053491b8)
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/lintcmd/runner/runner.go:762 +0x102
honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers(0xc0000bde00, 0xc0002d7320, 0xc0014fc550)
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/lintcmd/runner/runner.go:1007 +0x786
honnef.co/go/tools/lintcmd/runner.(*subrunner).doUncached(0x0, 0xc0002d7320)
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/lintcmd/runner/runner.go:666 +0x1a9
honnef.co/go/tools/lintcmd/runner.(*subrunner).do(0xc0000bde00, {0x9738e0, 0xc0002d7320})
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/lintcmd/runner/runner.go:529 +0x6e8
honnef.co/go/tools/lintcmd/runner.(*Runner).Run.func2({0x9738e0, 0xc0002d7320})
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/lintcmd/runner/runner.go:1183 +0x30
honnef.co/go/tools/lintcmd/runner.genericHandle({0x9738e0, 0xc0002d7320}, {0x9738e0, 0xc0002d7200}, 0x0, 0xc0001fa0b8, 0xc0001deb30)
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/lintcmd/runner/runner.go:762 +0x102
created by honnef.co/go/tools/lintcmd/runner.(*Runner).Run
        /home/christoph/go/pkg/mod/honnef.co/go/tools@v0.2.2/lintcmd/runner/runner.go:1182 +0x4d4
exit status 2
```

You can easily reproduce the error by running:

```
git clone git@gitlab.com:cznic/libc.git
cd libc
go run honnef.co/go/tools/cmd/staticcheck@v0.2.2 -debug.run-quickfix-analyzers
```

staticcheck version:
```
❯ go run honnef.co/go/tools/cmd/staticcheck@v0.2.2 -debug.version               
staticcheck 2021.1.2 (v0.2.2)

Compiled with Go version: go1.17.3
Main module:
        honnef.co/go/tools@v0.2.2 (sum: h1:MNh1AVMyVX23VUHE2O27jm6lNj3vjO5DexS4A1xvnzk=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
        golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
        golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
        golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
```

**Comment by dominikh** [comment]
Reproducer:

```
func fn() {
	_ = !(func() bool {
		return true
	}() && func() bool {
		return true
	}())
}
```

caused by us calling astutil.CopyExpr, which doesn't support ast.FuncLit.
