### ISSUE TITLE
panic: interface conversion: types.Type is nil, not *types.Signature

### ISSUE THREAD

**Issue by tarangv** [dominikh/go-tools#1141]
```
# staticcheck -version
staticcheck 2021.1 (v0.2.0)

# staticcheck -debug.version
staticcheck 2021.1 (v0.2.0)

Compiled with Go version: go1.17.2
Main module:
	honnef.co/go/tools
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
	golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
	golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)

# go version
go version go1.17.2 linux/amd64
```

Command run:
(from the pkg directory):
staticcheck

Code is private, and I have not isolated which line of code is causing this.

```
panic: interface conversion: types.Type is nil, not *types.Signature
goroutine 10158 [running]:
honnef.co/go/tools/go/ir.(*builder).expr0(0xc0025a3b00, 0xc0018e2b40, {0x95e530, 0xc001da1a40}, {0x0, {0x0, 0x0}, {0x0, 0x0}})
	/go/go-tools/go/ir/builder.go:640 +0x22fb
honnef.co/go/tools/go/ir.(*builder).expr(0x839260, 0xc0018e2b40, {0x95e530, 0xc001da1a40})
	/go/go-tools/go/ir/builder.go:500 +0x1db
honnef.co/go/tools/go/ir.(*builder).expr0(0xc0025a3b00, 0xc0018e2b40, {0x95e7a0, 0xc006afb098}, {0x2, {0x95cf80, 0xc00c31e600}, {0x0, 0x0}})
	/go/go-tools/go/ir/builder.go:658 +0x1dc5
honnef.co/go/tools/go/ir.(*builder).expr(0x839260, 0xc0018e2b40, {0x95e7a0, 0xc006afb098})
	/go/go-tools/go/ir/builder.go:500 +0x1db
honnef.co/go/tools/go/ir.(*builder).setCallFunc(0x90, 0xc0018e2b40, 0xc001df0240, 0xc03b0ce9d8)
	/go/go-tools/go/ir/builder.go:837 +0x2ec
honnef.co/go/tools/go/ir.(*builder).setCall(0x83a700, 0xc0018e2b40, 0xc001df0240, 0xc03b0ce9d8)
	/go/go-tools/go/ir/builder.go:917 +0x31
honnef.co/go/tools/go/ir.(*builder).expr0(0xc0025a3b00, 0xc0018e2b40, {0x95e230, 0xc001df0240}, {0x7, {0x95cfa8, 0xc002517f20}, {0x0, 0x0}})
	/go/go-tools/go/ir/builder.go:557 +0x21e6
honnef.co/go/tools/go/ir.(*builder).expr(0x96b948, 0xc0018e2b40, {0x95e230, 0xc001df0240})
	/go/go-tools/go/ir/builder.go:500 +0x1db
honnef.co/go/tools/go/ir.(*builder).assign(0x95e530, 0xc001da1a00, {0x960200, 0xc002965020}, {0x95e230, 0xc001df0240}, 0x30, 0xc0025a2b78, {0x95c530, 0xc001df0280})
	/go/go-tools/go/ir/builder.go:472 +0x485
honnef.co/go/tools/go/ir.(*builder).assignStmt(0xc001df0280, 0xc0018e2b40, {0xc001dee360, 0x1, 0xc001def770}, {0xc001dee390, 0x1, 0x60}, 0x1, {0x95c530, ...})
	/go/go-tools/go/ir/builder.go:1005 +0x29f
honnef.co/go/tools/go/ir.(*builder).stmt(0x88afc0, 0xc0018e2b40, {0x95e0b0, 0xc001df0280})
	/go/go-tools/go/ir/builder.go:2099 +0xa05
honnef.co/go/tools/go/ir.(*builder).stmtList(0x4, 0xc007268f00, {0xc0072d0380, 0x6, 0x10})
	/go/go-tools/go/ir/builder.go:748 +0x67
honnef.co/go/tools/go/ir.(*builder).stmt(0xc0018e2b40, 0xc0018e2b40, {0x95e1d0, 0xc001de70e0})
	/go/go-tools/go/ir/builder.go:2185 +0xd05
honnef.co/go/tools/go/ir.(*builder).buildFunction(0xc0025a3b00, 0xc0018e2b40)
	/go/go-tools/go/ir/builder.go:2297 +0x44a
honnef.co/go/tools/go/ir.(*builder).buildExits(0xc0018e2480, 0xc0018e2480)
	/go/go-tools/go/ir/exits.go:162 +0xd10
honnef.co/go/tools/go/ir.(*builder).buildFunction(0xc0025a3b00, 0xc0018e2480)
	/go/go-tools/go/ir/builder.go:2312 +0x4cb
honnef.co/go/tools/go/ir.(*builder).buildExits(0xc0018e25a0, 0xc0018e25a0)
	/go/go-tools/go/ir/exits.go:162 +0xd10
honnef.co/go/tools/go/ir.(*builder).buildFunction(0xc0025a3b00, 0xc0018e25a0)
	/go/go-tools/go/ir/builder.go:2312 +0x4cb
honnef.co/go/tools/go/ir.(*builder).buildExits(0xc00177d200, 0xc00177d200)
	/go/go-tools/go/ir/exits.go:162 +0xd10
honnef.co/go/tools/go/ir.(*builder).buildFunction(0xc0025a3b00, 0xc00177d200)
	/go/go-tools/go/ir/builder.go:2312 +0x4cb
honnef.co/go/tools/go/ir.(*builder).buildFuncDecl(0x0, 0xc07ab38630, 0xc0012eb920)
	/go/go-tools/go/ir/builder.go:2335 +0x195
honnef.co/go/tools/go/ir.(*Package).build(0xc07ab38630)
	/go/go-tools/go/ir/builder.go:2441 +0xc52
sync.(*Once).doSlow(0xc006434000, 0xc00106e000)
	/usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
honnef.co/go/tools/go/ir.(*Package).Build(...)
	/go/go-tools/go/ir/builder.go:2359
honnef.co/go/tools/internal/passes/buildir.run(0xc0183d65b0)
	/go/go-tools/internal/passes/buildir/buildir.go:86 +0x308
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0xc0068735f0, {0x966678, 0xc000eda000})
	/go/go-tools/lintcmd/runner/runner.go:937 +0x614
honnef.co/go/tools/lintcmd/runner.genericHandle({0x966678, 0xc000eda000}, {0x966678, 0xc0261c7ae0}, 0x0, 0xc0003260b8, 0xc00686aba0)
	/go/go-tools/lintcmd/runner/runner.go:762 +0x102
created by honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers
	/go/go-tools/lintcmd/runner/runner.go:1003 +0x725
```

**Comment by dominikh** [comment]
> Code is private, and I have not isolated which line of code is causing this.

Unless you want to give me access to the code I'm afraid you'll have to find out which piece of code is triggering this.

**Comment by tarangv** [comment]
Thanks dominikh for the quick response!

I isolated the issue to the use of new Go 1.17 type called `unsafe.Slice`.
The code crashes with staticcheck, 
but it builds and runs fine with `go build`

```go
package main

import "C"
import (
	"fmt"
        "unsafe"
)

func main() {
	size := 100
	ptr := C.malloc(C.size_t(size))

         // This line causes the crash
	ptrSlice := unsafe.Slice((*byte)(ptr), size)

        // Following line which is equivalent to above works.
	//ptrSlice := (*[1 << 30]byte)(ptr)[:size:size]

	fmt.Printf("ptrSlice len %v\n", len(ptrSlice))
}
```

**Comment by dominikh** [comment]
Ah. Please update to at least Staticcheck 2021.1.1. You're using an outdated version of Staticcheck, one that doesn't support unsafe.Slice yet.
