### ISSUE TITLE
gosimple: panics on type conversion

### ISSUE THREAD

**Issue by dnephin** [dominikh/go-tools#125]
gosimple suggests this type conversion, but then panics if the change is made:

https://github.com/docker/cli/commit/2bfac7fcdafeafbd2f450abb6d1bb3106e4f3ccb

```
panic: in github.com/docker/cli/cli/command/service.convertNetworks: cannot convert *t0 (github.com/docker/cli/opts.NetworkAttachmentOpts) to github.com/docker/cli/vendor/github.com/docker/docker/api/types/swarm.NetworkAttachmentConfig

goroutine 2412 [running]:
honnef.co/go/tools/ssa.emitConv(0xc42f0b9a40, 0x8428c0, 0xc4329a2c00, 0x83e720, 0xc43acc6660, 0xc4329a2c00, 0xc446241cc0)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/emit.go:244 +0x9e5
honnef.co/go/tools/ssa.(*builder).expr0(0xc438237d00, 0xc42f0b9a40, 0x83f1a0, 0xc423994340, 0x7, 0x83e720, 0xc43acc6660, 0x0, 0x0, 0x83f5a0, ...)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:573 +0x30f0
honnef.co/go/tools/ssa.(*builder).expr(0xc438237d00, 0xc42f0b9a40, 0x83f1a0, 0xc423994340, 0x1, 0xc435d344a0)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:530 +0x299
honnef.co/go/tools/ssa.(*builder).emitCallArgs(0xc438237d00, 0xc42f0b9a40, 0xc44623cd20, 0xc423994380, 0xc435d344a0, 0x0, 0x1, 0xc423994380, 0xc438236720, 0x40edf8)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:906 +0x30e
honnef.co/go/tools/ssa.(*builder).setCall(0xc438237d00, 0xc42f0b9a40, 0xc423994380, 0xc4280edec0)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:969 +0x11a
honnef.co/go/tools/ssa.(*builder).expr0(0xc438237d00, 0xc42f0b9a40, 0x83f1a0, 0xc423994380, 0x7, 0x83e7e0, 0xc44622d9b0, 0x0, 0x0, 0x0, ...)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:596 +0x334f
honnef.co/go/tools/ssa.(*builder).expr(0xc438237d00, 0xc42f0b9a40, 0x83f1a0, 0xc423994380, 0x7f4a1bdfd0d0, 0x0)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:530 +0x299
honnef.co/go/tools/ssa.(*builder).assign(0xc438237d00, 0xc42f0b9a40, 0x8402e0, 0xc43af52630, 0x83f1a0, 0xc423994380, 0xc43af52600, 0xc438236cd0)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:502 +0x137
honnef.co/go/tools/ssa.(*builder).assignStmt(0xc438237d00, 0xc42f0b9a40, 0xc42765a080, 0x1, 0x1, 0xc42765a0d0, 0x1, 0x1, 0xc438236d00)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:1050 +0x3ed
honnef.co/go/tools/ssa.(*builder).stmt(0xc438237d00, 0xc42f0b9a40, 0x83efa0, 0xc4239943c0)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:2010 +0x2a02
honnef.co/go/tools/ssa.(*builder).stmtList(0xc438237d00, 0xc42f0b9a40, 0xc423994300, 0x4, 0x4)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:790 +0x61
honnef.co/go/tools/ssa.(*builder).stmt(0xc438237d00, 0xc42f0b9a40, 0x83f120, 0xc424cbfa70)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:2106 +0x2df7
honnef.co/go/tools/ssa.(*builder).rangeStmt(0xc438237d00, 0xc42f0b9a40, 0xc423b3a5a0, 0x0)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:1953 +0x4a3
honnef.co/go/tools/ssa.(*builder).stmt(0xc438237d00, 0xc42f0b9a40, 0x83f820, 0xc423b3a5a0)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:2144 +0x1e69
honnef.co/go/tools/ssa.(*builder).stmtList(0xc438237d00, 0xc42f0b9a40, 0xc423994480, 0x4, 0x4)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:790 +0x61
honnef.co/go/tools/ssa.(*builder).stmt(0xc438237d00, 0xc42f0b9a40, 0x83f120, 0xc424cbfad0)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:2106 +0x2df7
honnef.co/go/tools/ssa.(*builder).buildFunction(0xc438237d00, 0xc42f0b9a40)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:2199 +0x35c
honnef.co/go/tools/ssa.(*builder).buildFuncDecl(0xc438237d00, 0xc439fc8360, 0xc424cbfb30)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:2229 +0x12e
honnef.co/go/tools/ssa.(*Package).build(0xc439fc8360)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:2349 +0x691
honnef.co/go/tools/ssa.(*Package).(honnef.co/go/tools/ssa.build)-fm()
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:2264 +0x2a
sync.(*Once).Do(0xc439fc838c, 0xc4348eef98)
        /usr/local/go/src/sync/once.go:44 +0xbe
honnef.co/go/tools/ssa.(*Package).Build(0xc439fc8360)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:2264 +0x55
honnef.co/go/tools/ssa.(*Program).Build.func1(0xc437b20360, 0xc439fc8360)
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:2248 +0x2b
created by honnef.co/go/tools/ssa.(*Program).Build
        /go/src/gopkg.in/dnephin/gometalinter.v1/_linters/src/honnef.co/go/tools/ssa/builder.go:2250 +0x141
```

Haven't had a chance to look into it yet, or compare against master, but I want to preserve the stacktrace  somewhere.

**Comment by dominikh** [comment]
This was fixed in https://github.com/dominikh/go-tools/commit/769824fffc0626f9febdcdeb1c80d3644c12e788

**Comment by dnephin** [comment]
Thanks!
