### ISSUE TITLE
gosimple - panic: unexpected Object type: builtin unsafe.Alignof

### ISSUE THREAD

**Issue by udhos** [dominikh/go-tools#127]
What is this error? 

go version is: go1.9beta2 linux/amd64

```
esmarques@RickDeckard:~/go/src/github.com/udhos/fugo$ gosimple github.com/udhos/fugo/arena
panic: unexpected Object type: builtin unsafe.Alignof

goroutine 1 [running]:
honnef.co/go/ssa.memberFromObject(0xc423dfc060, 0x85d160, 0xc42007d3b0, 0x0, 0x0)
	/home/esmarques/go/src/honnef.co/go/ssa/create.go:103 +0xe0f
honnef.co/go/ssa.(*Program).CreatePackage(0xc423d8e280, 0xc42007c3c0, 0x0, 0x0, 0x0, 0x0, 0xc423d7bf01, 0xc423d7bf80)
	/home/esmarques/go/src/honnef.co/go/ssa/create.go:196 +0x796
honnef.co/go/lint.buildPackage.func1(0xc422101170, 0x2, 0x2)
	/home/esmarques/go/src/honnef.co/go/lint/lint.go:99 +0x11f
honnef.co/go/lint.buildPackage.func1(0xc42287a6c0, 0x3, 0x4)
	/home/esmarques/go/src/honnef.co/go/lint/lint.go:100 +0x14b
honnef.co/go/lint.buildPackage.func1(0xc422368780, 0x8, 0x8)
	/home/esmarques/go/src/honnef.co/go/lint/lint.go:100 +0x14b
honnef.co/go/lint.buildPackage.func1(0xc423d82080, 0x4, 0x4)
	/home/esmarques/go/src/honnef.co/go/lint/lint.go:100 +0x14b
honnef.co/go/lint.buildPackage(0xc42010c140, 0xc423d800d0, 0x1, 0x1, 0xc4200fe0f0, 0xc4200e0040, 0x40, 0x1b)
	/home/esmarques/go/src/honnef.co/go/lint/lint.go:104 +0x303
honnef.co/go/lint.(*Linter).Lint(0xc423d7de00, 0xc4200e0080, 0x6)
	/home/esmarques/go/src/honnef.co/go/lint/lint.go:134 +0x116
honnef.co/go/lint/lintutil.(*runner).lint(0xc4200c61e0, 0xc4200e0080, 0x0)
	/home/esmarques/go/src/honnef.co/go/lint/lintutil/util.go:166 +0x95
honnef.co/go/lint/lintutil.ProcessArgs(0x6fd307, 0x8, 0x858380, 0x892ca8, 0xc42000a070, 0x1, 0x1)
	/home/esmarques/go/src/honnef.co/go/lint/lintutil/util.go:148 +0xafe
main.main()
	/home/esmarques/go/src/honnef.co/go/simple/cmd/gosimple/gosimple.go:11 +0xa2
esmarques@RickDeckard:~/go/src/github.com/udhos/fugo$ 
esmarques@RickDeckard:~/go/src/github.com/udhos/fugo$ go version
go version go1.9beta2 linux/amd64
esmarques@RickDeckard:~/go/src/github.com/udhos/fugo$ 

```

**Comment by udhos** [comment]
Sorry, I was using the older honnef.co/go/simple/cmd/gosimple.
Switched to the new honnef.co/go/tools/cmd/gosimple.
