### ISSUE TITLE
"cannot convert" panic with the latest tip version of Go

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#1335]
```
$ staticcheck -version
staticcheck (devel, v0.4.0-0.dev.0.20221004230109-4229c3d955f8)
$ go version
go version devel go1.20-205f636e0a Fri Nov 18 08:04:52 2022 +0000 linux/amd64
$ staticcheck net/netip
panic: in net/netip.AddrFromSlice: cannot convert Load <[]byte> t0 ([]byte) to [4]byte

goroutine 232 [running]:
honnef.co/go/tools/go/ir.emitConv(0xc0016a4000, {0xa00e80, 0xc001591b20}, {0x9fc030?, 0xc000ba4258}, {0x9fb860, 0xc000957800})
	/home/mvdan/go/pkg/mod/honnef.co/go/tools@v0.4.0-0.dev.0.20221004230109-4229c3d955f8/go/ir/emit.go:293 +0xc05
honnef.co/go/tools/go/ir.(*builder).expr0(0xc000b63b50, 0xc0016a4000, {0x9fd448?, 0xc000957800?}, {0x7, {0x9fc030, 0xc000ba4258}, {0x0, 0x0}})
	/home/mvdan/go/pkg/mod/honnef.co/go/tools@v0.4.0-0.dev.0.20221004230109-4229c3d955f8/go/ir/builder.go:610 +0x5d7
honnef.co/go/tools/go/ir.(*builder).expr(0xc00077fbd8?, 0xc0016a4000, {0x9fd448, 0xc000957800})
	/home/mvdan/go/pkg/mod/honnef.co/go/tools@v0.4.0-0.dev.0.20221004230109-4229c3d955f8/go/ir/builder.go:566 +0x1e7
[...]
```

**Comment by dominikh** [comment]
This is because we don't yet handle Go 1.20's new "slice to array" conversion.

**Comment by aarongable** [comment]
It looks like this fix has not yet been included in a tagged release. Now that go1.20 has been officially released, when do we expect a new version of this repo to be released?
