### ISSUE TITLE
false positive SA4023: this comparison is always true

### ISSUE THREAD

**Issue by qiuchengxuan** [dominikh/go-tools#1436]
**environment**

```
staticcheck -version
staticcheck 2023.1.5 (v0.4.5)

staticcheck -debug.version
staticcheck 2023.1.5 (v0.4.5)

Compiled with Go version: devel go1.22-7c2b69080a Thu Aug 10 17:34:27 2023 +0000
Main module:
        honnef.co/go/tools@v0.4.5 (sum: h1:YGD4H+SuIOOqsyoLOpZDWcieM28W47/zRO7f+9V3nvo=)
Dependencies:
        github.com/BurntSushi/toml@v1.2.1 (sum: h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=)
        golang.org/x/exp/typeparams@v0.0.0-20221208152030-732eee02a75a (sum: h1:Jw5wfR+h9mnIYH+OtGT2im5wV1YGGDora5vTv/aa5bE=)
        golang.org/x/mod@v0.10.0 (sum: h1:lFO9qtOdlre5W1jxS3r/4szv2/6iXxScdzjoBMXNhYk=)
        golang.org/x/sys@v0.8.0 (sum: h1:EBmGv8NaZBZTWvrbjNoL6HVt+IVy3QDQpJs7VRIw3tU=)
        golang.org/x/tools@v0.9.4-0.20230601214343-86c93e8732cc (sum: h1:mqZawFxUzsv+YVwGQO30cZegeV/YD6dAwsdGxi0tQQg=)

go version && go env
go version go1.20.4 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1186572775=/tmp/go-build -gno-record-gcc-switches"
```

**example**

```go
package main

import (
        "fmt"
        "io"
        "os"
)

type container[T any] struct {
        t T
}

func (c *container[T]) FuncAny(fn func(t *T) any) any {
        return fn(&c.t)
}

type whatever struct {
        c container[io.Closer]
}

func (w *whatever) Close() error {
        return w.c.FuncAny(func(closer *io.Closer) any {
                return (*closer).Close()
        }).(error)
}

func main() {
        file, _ := os.Open("/tmp/whatever.txt")
        w := whatever{container[io.Closer]{file}}
        if err := w.Close(); err != nil {
                fmt.Println("error")
        }
}
```

**cmmand and output**

```bash
staticcheck test.go
test.go:30:23: this comparison is always true (SA4023)
        test.go:30:12: the lhs of the comparison is the 1st return value of this function call
        test.go:21:20: (*command-line-arguments.whatever).Close never returns a nil interface value
```

**Comment by dominikh** [comment]
Not a false positive. Your type assertion in `whatever.Close` implies that that the return value will always be non-nil. If it were nil, the type assertion would fail and panic:

```
$ go run bar.go          
panic: interface conversion: interface is nil, not error

goroutine 1 [running]:
main.(*whatever).Close(0x496456?)
	/home/dominikh/prj/src/example.com/bar.go:24 +0x39
main.main()
	/home/dominikh/prj/src/example.com/bar.go:30 +0x45
exit status 2
```
