### ISSUE TITLE
invalid memory address or nil pointer dereference in the (*MethodSetCache).MethodSet

### ISSUE THREAD

**Issue by hawkingrei** [dominikh/go-tools#1469]
https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/48188/tiprow_fast_test/1722103907590606848

```
 compilepkg: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb1ed33]
goroutine 574 [running]:
go/types.methodSet.add(0x4dee80?, {0x0, 0x1, 0xc004336170?}, {0x0, 0x0, 0xd0?}, 0xd0?, 0x0?)
	GOROOT/src/go/types/methodset.go:222 +0xd3
go/types.NewMethodSet({0x4dee80?, 0xc005352690?})
	GOROOT/src/go/types/methodset.go:158 +0x8bd
golang.org/x/tools/go/types/typeutil.(*MethodSetCache).lookupNamed(0xc006410030, 0xc005352690)
	external/org_golang_x_tools/go/types/typeutil/methodsetcache.go:66 +0x8f
golang.org/x/tools/go/types/typeutil.(*MethodSetCache).MethodSet(0xc006410030, {0x4dee80, 0xc005352690})
	external/org_golang_x_tools/go/types/typeutil/methodsetcache.go:37 +0xaf
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4dee80?, 0xc005352690?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:166 +0xe5
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4defc0?, 0xc00b088840?}, 0x1)
	external/co_honnef_go_tools/go/ir/methods.go:230 +0x5a6
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4dee80?, 0xc005352380?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:223 +0x419
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4defe8?, 0xc00a969b20?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:195 +0x273
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4df010?, 0xc00af66f48?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:235 +0x4d2
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4dee80?, 0xc0053523f0?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:183 +0x1b5
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4def98?, 0xc00a9690d0?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:198 +0x2a5
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4df010?, 0xc00af669a8?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:235 +0x4d2
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4defe8?, 0xc001b60f80?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:183 +0x1b5
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4defc0?, 0xc001e1aba0?}, 0x1)
	external/co_honnef_go_tools/go/ir/methods.go:230 +0x5a6
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4dee80?, 0xc0007c5ea0?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:223 +0x419
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4defe8?, 0xc001e15d70?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:195 +0x273
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4defc0?, 0xc001e1ac60?}, 0x1)
	external/co_honnef_go_tools/go/ir/methods.go:230 +0x5a6
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4dee80?, 0xc0007c5e30?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:223 +0x419
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4defe8?, 0xc001e15e50?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:195 +0x273
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4defc0?, 0xc001e1acc0?}, 0x1)
	external/co_honnef_go_tools/go/ir/methods.go:230 +0x5a6
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4dee80?, 0xc0007c56c0?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:223 +0x419
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4defe8?, 0xc001e15e60?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:195 +0x273
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4df010?, 0xc001e23d40?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:235 +0x4d2
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4dee80?, 0xc0007c5650?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:183 +0x1b5
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4df010?, 0xc001e23ed8?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:235 +0x4d2
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4dee80?, 0xc0007c5500?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:184 +0x1d4
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4df010?, 0xc0055bd8f0?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:235 +0x4d2
honnef.co/go/tools/go/ir.(*Program).needMethods(0xc006410000, {0x4df038?, 0xc001c4b2c0?}, 0x0)
	external/co_honnef_go_tools/go/ir/methods.go:211 +0x365
honnef.co/go/tools/go/ir.(*Program).needMethodsOf(0xc006410000, {0x4df038?, 0xc001c4b2c0?})
	external/co_honnef_go_tools/go/ir/methods.go:148 +0x70
honnef.co/go/tools/go/ir.(*Package).build(0xc000eeeab0)
	external/co_honnef_go_tools/go/ir/builder.go:2568 +0xf6
sync.(*Once).doSlow(0xc006410000?, 0xc000121b00?)
	GOROOT/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
	GOROOT/src/sync/once.go:65
honnef.co/go/tools/go/ir.(*Package).Build(...)
	external/co_honnef_go_tools/go/ir/builder.go:2556
honnef.co/go/tools/internal/passes/buildir.run(0xc00640c0d0)
	external/co_honnef_go_tools/internal/passes/buildir/buildir.go:86 +0x1a8
main.(*action).execOnce(0xc000f49360)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:353 +0x8d7
sync.(*Once).doSlow(0x900000a00?, 0x1020014050a0014?)
	GOROOT/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
	GOROOT/src/sync/once.go:65
main.(*action).exec(...)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:280
main.execAll.func1(0x114a00001000000?)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:274 +0x72
created by main.execAll in goroutine 515
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:272 +0x48 
```

```
honnef.co/go/tools v0.4.6
```

**Comment by dominikh** [comment]
Cannot reproduce.

The following finishes without panicking: 
```
$ git clone https://github.com/pingcap/tidb.git
$ cd tidb
$ staticcheck ./...
```

**Comment by dominikh** [comment]
Timed out.
