### ISSUE TITLE
Support GOEXPERIMENT=rangefunc

### ISSUE THREAD

**Issue by tamayika** [dominikh/go-tools#1494]
Currently, staticcheck can not analyze and panic `for range iter` with `GOEXPERIMENT=rangefunc`

```go
package main

import (
	"iter"
)

func main() {
	var (
		iter iter.Seq[int]
	)
	for _ = range iter {

	}
}
```

Stacktrace
```
panic: Cannot range over: func(yield func(int) bool)

goroutine 140 [running]:
honnef.co/go/tools/go/ir.(*builder).rangeStmt(0xc000483a60, 0xc000598000, 0xc000359da0, 0x0, {0xaa09d0, 0xc000359da0})
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/go/ir/builder.go:2214 +0x894
honnef.co/go/tools/go/ir.(*builder).stmt(0xc000483a60, 0xc000598000, {0xaa25c0?, 0xc000359da0?})
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/go/ir/builder.go:2427 +0x20a
honnef.co/go/tools/go/ir.(*builder).stmtList(...)
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/go/ir/builder.go:847
honnef.co/go/tools/go/ir.(*builder).stmt(0xc000483a60, 0xc000598000, {0xaa2410?, 0xc000283980?})
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/go/ir/builder.go:2385 +0x1447
honnef.co/go/tools/go/ir.(*builder).buildFunction(0xc000483a60, 0xc000598000)
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/go/ir/builder.go:2497 +0x417
honnef.co/go/tools/go/ir.(*builder).buildFuncDecl(0xc00033da60, 0xc00019cf30, 0xc000283b60)
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/go/ir/builder.go:2534 +0x189
honnef.co/go/tools/go/ir.(*Package).build(0xc00019cf30)
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/go/ir/builder.go:2638 +0xb46
sync.(*Once).doSlow(0xc0003ce460?, 0xc000359c80?)
        C:/Program Files/Go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        C:/Program Files/Go/src/sync/once.go:65
honnef.co/go/tools/go/ir.(*Package).Build(...)
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/go/ir/builder.go:2556
honnef.co/go/tools/internal/passes/buildir.run(0xc0002ffe10)
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/internal/passes/buildir/buildir.go:86 +0x1b1
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0xc000458420, {0xaa4de8?, 0xc00044a140})
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/lintcmd/runner/runner.go:992 +0x71b
honnef.co/go/tools/lintcmd/runner.genericHandle({0xaa4de8, 0xc00044a140}, {0xaa4de8?, 0xc00044a000?}, 0xc00043c360, 0xc0001e5ac0, 0xc000419d50)
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/lintcmd/runner/runner.go:817 +0x11f
created by honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers in goroutine 136
        C:/Users/Owner/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20231215165614-a367d57f6820/lintcmd/runner/runner.go:1061 +0x6a6
```

**Comment by timothy-king** [comment]
cc'ed @dominikh on go.dev/cl/555075.

**Comment by dominikh** [comment]
I don't think Staticcheck will support ranging over functions until the feature is no longer experimental. I'd like to wait for the semantics to be finalized first.

**Comment by pomo-mondreganto** [comment]
I believe it's worth noticing that the lack of support for `rangefunc` in `staticcheck` effectively blocks a lot of projects from using and experimenting with the iterators, as their CI pipelines will fail.

**Comment by ianlancetaylor** [comment]
Just a note that rangefunc is no longer experimental.  It's now part of the main branch of Go development, though not yet released.

**Comment by dominikh** [comment]
@fzipp should be fixed now.
