### ISSUE TITLE
go to definition panic

### ISSUE THREAD

**Issue by john-behm-bertelsmann** [dominikh/go-tools#1507]
staticcheck 2023.1.7 (v0.4.7)
```shell
staticcheck -debug.version
staticcheck 2023.1.7 (v0.4.7)

Compiled with Go version: go1.21.6
Main module:
        honnef.co/go/tools@v0.4.7 (sum: h1:9MDAWxMoSnB6QoSqiVr7P5mtkT9pOc1kSxchzPCnqJs=)
Dependencies:
        github.com/BurntSushi/toml@v1.2.1 (sum: h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=)
        golang.org/x/exp/typeparams@v0.0.0-20221208152030-732eee02a75a (sum: h1:Jw5wfR+h9mnIYH+OtGT2im5wV1YGGDora5vTv/aa5bE=)
        golang.org/x/mod@v0.12.0 (sum: h1:rmsUpXtvNzj340zd98LZ4KntptpfRHwpFOHG188oHXc=)
        golang.org/x/sys@v0.11.0 (sum: h1:eG7RXZHdqOJ1i+0lgLgCpSXAp6M3LYlAo6osgSi0xOM=)
        golang.org/x/tools@v0.12.1-0.20230825192346-2191a27a6dc5 (sum: h1:Vk4mysSz+GqQK2eqgWbo4zEO89wkeAjJiFIr9bpqa8k=)
```
```shell
/home/behm/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/bin/go
```

```

GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/behm/.cache/go-build'
GOENV='/home/behm/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/behm/go/pkg/mod'
GONOPROXY='*redacted*'
GONOSUMDB='*redacted*'
GOOS='linux'
GOPATH='/home/behm/go'
GOPRIVATE='*redacted*'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.6'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4048975720=/tmp/go-build -gno-record-gcc-switches'
```
- Exactly which command you ran: it's alt + click on some symbol in VS Code
- Sadly I cannot share the code but seemingly nil pointers are passed to `ir.memberFromObject`

```
Error while running tool: /home/behm/go/bin/staticcheck
2024-03-25 11:14:16.335 [error] panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x713752]

goroutine 869 [running]:
honnef.co/go/tools/go/ir.memberFromObject(0xc008562090, {0x0, 0x0?}, {0x0?, 0x0})
	/home/behm/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/create.go:54 +0x52
honnef.co/go/tools/go/ir.membersFromDecl(0xc008562090, {0xa02bf8?, 0xc00211b6c0?})
	/home/behm/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/create.go:155 +0x297
honnef.co/go/tools/go/ir.(*Program).CreatePackage(0xc0003fa000, 0xc0018b1920, {0xc003bb1d80, 0x2, 0x2}, 0xc005716ff0, 0x0)
	/home/behm/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/create.go:207 +0x7a5
honnef.co/go/tools/internal/passes/buildir.run(0xc000f4e0d0)
	/home/behm/go/pkg/mod/honnef.co/go/tools@v0.4.7/internal/passes/buildir/buildir.go:85 +0x165
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0xc003056000, {0xa04548?, 0xc008488a00})
	/home/behm/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:992 +0x6fd
honnef.co/go/tools/lintcmd/runner.genericHandle({0xa04548?, 0xc008488a00}, {0xa04548?, 0xc008488960?}, 0x0?, 0xc0003d7c60, 0xc002539f10)
	/home/behm/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:817 +0x129
created by honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers in goroutine 868
	/home/behm/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:1061 +0x6b5
```

**Comment by timothy-king** [comment]
My bet is this almost certainly a symptom of https://go.dev/issue/66525 . Try recompiling staticcheck with >=go1.22.0.
