### ISSUE TITLE
Staticcheck crashes with Go 1.22

### ISSUE THREAD

**Issue by slaskawi** [dominikh/go-tools#1531]
# Summary

The staticcheck command crashes with the Go 1.22:

```
staticcheck ./...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x1010f6f1c]

goroutine 119 [running]:
honnef.co/go/tools/go/ir.memberFromObject(0x1400158c1b0, {0x0, 0x0?}, {0x0?, 0x0})
	honnef.co/go/tools/go/ir/create.go:54 +0x3c
honnef.co/go/tools/go/ir.membersFromDecl(0x1400158c1b0, {0x1013ca858?, 0x140017820c0?})
	honnef.co/go/tools/go/ir/create.go:137 +0x378
honnef.co/go/tools/go/ir.(*Program).CreatePackage(0x1400198e000, 0x140017ae060, {0x140017b0000, 0x1, 0x1}, 0x140017b2050, 0x0)
	honnef.co/go/tools/go/ir/create.go:207 +0x76c
honnef.co/go/tools/internal/passes/buildir.run(0x14001696410)
	honnef.co/go/tools/internal/passes/buildir/buildir.go:85 +0x108
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0x140018908d0, {0x1013cc1c8?, 0x140003eaaa0})
	honnef.co/go/tools/lintcmd/runner/runner.go:992 +0x61c
honnef.co/go/tools/lintcmd/runner.genericHandle({0x1013cc1c8?, 0x140003eaaa0}, {0x1013cc1c8?, 0x140003ea960?}, 0x101363b40?, 0x0, 0x14001585030)
	honnef.co/go/tools/lintcmd/runner/runner.go:817 +0x11c
honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers(0x14000166a00, 0x140015317a0, 0x140017b2000)
	honnef.co/go/tools/lintcmd/runner/runner.go:1065 +0x5d0
honnef.co/go/tools/lintcmd/runner.(*subrunner).doUncached(0x4?, 0x140015317a0)
	honnef.co/go/tools/lintcmd/runner/runner.go:720 +0x160
honnef.co/go/tools/lintcmd/runner.(*subrunner).do(0x14000166a00, {0x1013cc210?, 0x140015317a0})
	honnef.co/go/tools/lintcmd/runner/runner.go:577 +0x700
honnef.co/go/tools/lintcmd/runner.(*Runner).Run.func2({0x1013cc210?, 0x140015317a0?})
	honnef.co/go/tools/lintcmd/runner/runner.go:1268 +0x34
honnef.co/go/tools/lintcmd/runner.genericHandle({0x1013cc210?, 0x140015317a0}, {0x1013cc210?, 0x1400148ab40?}, 0x0?, 0x14000371e00, 0x14001580000)
	honnef.co/go/tools/lintcmd/runner/runner.go:817 +0x11c
created by honnef.co/go/tools/lintcmd/runner.(*Runner).Run in goroutine 1
	honnef.co/go/tools/lintcmd/runner/runner.go:1267 +0x498
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x1010f6f1c]

goroutine 178 [running]:
honnef.co/go/tools/go/ir.memberFromObject(0x1400168c480, {0x0, 0x0?}, {0x1013c8ad8?, 0x14001824750})
	honnef.co/go/tools/go/ir/create.go:54 +0x3c
honnef.co/go/tools/go/ir.membersFromDecl(0x1400168c480, {0x1013caca8?, 0x14001824750?})
	honnef.co/go/tools/go/ir/create.go:163 +0xfc
honnef.co/go/tools/go/ir.(*Program).CreatePackage(0x14000128000, 0x14000d3e420, {0x140017b04b8, 0x1, 0x1}, 0x140017222d0, 0x0)
	honnef.co/go/tools/go/ir/create.go:207 +0x76c
honnef.co/go/tools/internal/passes/buildir.run(0x140017b6750)
	honnef.co/go/tools/internal/passes/buildir/buildir.go:85 +0x108
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0x14000192b10, {0x1013cc1c8?, 0x1400053e1e0})
	honnef.co/go/tools/lintcmd/runner/runner.go:992 +0x61c
honnef.co/go/tools/lintcmd/runner.genericHandle({0x1013cc1c8?, 0x1400053e1e0}, {0x1013cc1c8?, 0x1400053e0a0?}, 0x101363b40?, 0x0, 0x14000887030)
	honnef.co/go/tools/lintcmd/runner/runner.go:817 +0x11c
honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers(0x14000166a00, 0x140015318c0, 0x14001722280)
	honnef.co/go/tools/lintcmd/runner/runner.go:1065 +0x5d0
honnef.co/go/tools/lintcmd/runner.(*subrunner).doUncached(0x4?, 0x140015318c0)
	honnef.co/go/tools/lintcmd/runner/runner.go:720 +0x160
honnef.co/go/tools/lintcmd/runner.(*subrunner).do(0x14000166a00, {0x1013cc210?, 0x140015318c0})
	honnef.co/go/tools/lintcmd/runner/runner.go:577 +0x700
honnef.co/go/tools/lintcmd/runner.(*Runner).Run.func2({0x1013cc210?, 0x140015318c0?})
	honnef.co/go/tools/lintcmd/runner/runner.go:1268 +0x34
honnef.co/go/tools/lintcmd/runner.genericHandle({0x1013cc210?, 0x140015318c0}, {0x1013cc210?, 0x1400148ab40?}, 0x0?, 0x14000371e00, 0x14001780000)
	honnef.co/go/tools/lintcmd/runner/runner.go:817 +0x11c
created by honnef.co/go/tools/lintcmd/runner.(*Runner).Run in goroutine 1
	honnef.co/go/tools/lintcmd/runner/runner.go:1267 +0x498
```

# Important information

```
$ staticcheck -version                                                                                                                                                                          2 
staticcheck 2023.1.6 (v0.4.6)

$ staticcheck -debug.version
staticcheck 2023.1.6 (v0.4.6)

Compiled with Go version: go1.21.1
Main module:
	honnef.co/go/tools
Dependencies:
	github.com/BurntSushi/toml@v1.2.1 (sum: h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=)
	golang.org/x/exp/typeparams@v0.0.0-20221208152030-732eee02a75a (sum: h1:Jw5wfR+h9mnIYH+OtGT2im5wV1YGGDora5vTv/aa5bE=)
	golang.org/x/mod@v0.12.0 (sum: h1:rmsUpXtvNzj340zd98LZ4KntptpfRHwpFOHG188oHXc=)
	golang.org/x/sys@v0.11.0 (sum: h1:eG7RXZHdqOJ1i+0lgLgCpSXAp6M3LYlAo6osgSi0xOM=)
	golang.org/x/tools@v0.12.1-0.20230825192346-2191a27a6dc5 (sum: h1:Vk4mysSz+GqQK2eqgWbo4zEO89wkeAjJiFIr9bpqa8k=)

$ go version
go version go1.22.2 darwin/arm64

$ go env                                                                                                                                                                                        1 ↵
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/sebastian.laskawiec/Library/Caches/go-build'
GOENV='/Users/sebastian.laskawiec/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/sebastian.laskawiec/.gvm/pkgsets/go1.22.2/global/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/sebastian.laskawiec/.gvm/pkgsets/go1.22.2/global'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/sebastian.laskawiec/.gvm/gos/go1.22.2'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/sebastian.laskawiec/.gvm/gos/go1.22.2/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/sebastian.laskawiec/.gvm/pkgsets/go1.18.3/main/src/github.com/10gen/ops-manager-kubernetes/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/fz/3m23bjqd64dg_r9wggfzldjr0000gp/T/go-build3179104440=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

**Comment by dominikh** [comment]
> Compiled with Go version: go1.21.1

Please build Staticcheck with Go 1.22.
