### ISSUE TITLE
Staticcheck panics upon running.

### ISSUE THREAD

**Issue by itsdevbear** [dominikh/go-tools#1560]
Version:
staticcheck (devel, v0.5.0-0.dev.0.20240603145629-dbad790edf7b)

Debug Version
Compiled with Go version: go1.22.4
Main module:
        honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b (sum: h1:zl2fQvNTKyinT2c/bPK1u2lE0UEydt0P0eFFSNwjHDA=)
Dependencies:
        github.com/BurntSushi/toml@v1.3.2 (sum: h1:o7IhLm0Msx3BaB+n3Ag7L8EVlByGnpq14C4YWiu/gL8=)
        golang.org/x/exp/typeparams@v0.0.0-20231108232855-2478ac86f678 (sum: h1:1P7xPZEwZMoBoz0Yze5Nx2/4pxj6nw9ZqHWXqP0iRgQ=)
        golang.org/x/mod@v0.17.0 (sum: h1:zY54UmvipHiNd+pm+m0x9KhZ9hl1/7QNMyxXbc6ICqA=)
        golang.org/x/sync@v0.7.0 (sum: h1:YsImfSBoP9QPYL0xyKJPq0gcaJdG3rInoqxTWbfQu9M=)
        golang.org/x/tools@v0.21.1-0.20240531212143-b6235391adb3 (sum: h1:SHq4Rl+B7WvyM4XODon1LXtP7gcG49+7Jubt1gWWswY=)

Golang Version
go version go1.22.4 darwin/arm64
```
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/dev/Library/Caches/go-build'
GOENV='/Users/dev/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/dev/go/pkg/mod'
GONOPROXY='github.com/berachain'
GONOSUMDB='github.com/berachain'
GOOS='darwin'
GOPATH='/Users/dev/go'
GOPRIVATE='github.com/berachain'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.22.4/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.22.4/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.4'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK='/Users/dev/code/v2/beacon-kit/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/kl/ztx913ks407bswv6rl79gbm80000gn/T/go-build2895411506=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

```
panic: internal error: unhandled type *ir.MultiConvert

goroutine 2079 [running]:
honnef.co/go/tools/analysis/facts/nilness.impl.func1({0x104fda6e8, 0x140035aca50})
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/analysis/facts/nilness/nilness.go:234 +0xb34
honnef.co/go/tools/analysis/facts/nilness.impl.func1({0x104fda208, 0x1400947cc80})
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/analysis/facts/nilness/nilness.go:147 +0xbf4
honnef.co/go/tools/analysis/facts/nilness.impl(0x14015f78540, 0x14013cad1e0, 0x14008e90d38)
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/analysis/facts/nilness/nilness.go:241 +0x2e8
honnef.co/go/tools/analysis/facts/nilness.run(0x14015f78540)
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/analysis/facts/nilness/nilness.go:66 +0xf4
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0x140073ee0c0, {0x104fd8458?, 0x14014db4dc0})
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/lintcmd/runner/runner.go:986 +0x604
honnef.co/go/tools/lintcmd/runner.genericHandle({0x104fd8458, 0x14014db4dc0}, {0x104fd8458?, 0x14014db4b40?}, 0x1400553d0e0, 0x0, 0x14008e912b8)
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/lintcmd/runner/runner.go:811 +0x10c
honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers(0x1400014a460, 0x1400055d440, 0x140049b6b90)
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/lintcmd/runner/runner.go:1059 +0x5ac
honnef.co/go/tools/lintcmd/runner.(*subrunner).doUncached(0x1400014a460, 0x1400055d440)
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/lintcmd/runner/runner.go:714 +0x158
honnef.co/go/tools/lintcmd/runner.(*subrunner).do(0x1400014a460, {0x104fd84a0?, 0x1400055d440})
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/lintcmd/runner/runner.go:571 +0x76c
honnef.co/go/tools/lintcmd/runner.(*Runner).Run.func2({0x104fd84a0?, 0x1400055d440?})
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/lintcmd/runner/runner.go:1225 +0x34
honnef.co/go/tools/lintcmd/runner.genericHandle({0x104fd84a0, 0x1400055d440}, {0x104fd84a0?, 0x14000437320?}, 0x14000a1fc80, 0x140004484f0, 0x1401722d850)
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/lintcmd/runner/runner.go:811 +0x10c
created by honnef.co/go/tools/lintcmd/runner.(*Runner).Run in goroutine 1
        /Users/dev/go/pkg/mod/honnef.co/go/tools@v0.5.0-0.dev.0.20240603145629-dbad790edf7b/lintcmd/runner/runner.go:1224 +0x384
make: *** [staticcheck] Error 1
```

**Comment by arp242** [comment]
Having some code to reproduce this would be helpful.

**Comment by itsdevbear** [comment]
@arp242 sorry this feel through my inbox. 


Steps to Reproduce: 
1. https://github.com/berachain/beacon-kit 


2. re-enable statticcheck in `.golangci.yaml`

3. run `make format`

**Comment by arp242** [comment]
[~/beacon-kit](main)% staticcheck ./...
    -: pattern ./...: directory prefix . does not contain modules listed in go.work or their selected dependencies (compile)

I'm not going to spend time figuring out your project or make-soup. You're going to have to spend a minimum amount of effort to make this reproducible, where "reproducible" means "can be reproduced with a single staticcheck command".

**Comment by dominikh** [comment]
I generally agree. Issues should be reproducible in a minimal manner. They should especially not depend on build systems other than `go build`, and the problem has to reproduce with `staticcheck`, not any other (meta)linter that chooses to wrap us.

However, here's the trivial reproducer for the bug:

```
func foo[T []byte | string](s T) T {
	switch v := any(s).(type) {
	case string:
		return T(v)
	case []byte:
		return T(v)
	default:
		return s
	}
}
```
