### ISSUE TITLE
panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident

### ISSUE THREAD

**Issue by ldez** [dominikh/go-tools#1564]
I built staticcheck from 1f707279039d3d222dd3c06272724b173dbcb535 and tested on the [Kubernetes](https://github.com/kubernetes/kubernetes) code.

```
$ staticcheck -version
staticcheck (no version)
```

```
$ staticcheck -debug.version
staticcheck (no version)

Compiled with Go version: go1.22.3
Main module:
        honnef.co/go/tools
Dependencies:
        github.com/BurntSushi/toml@v1.4.1-0.20240526193622-a339e1f7089c (sum: h1:pxW6RcqyfI9/kWtOwnv/G+AzdKuy2ZrqINhenH4HyNs=)
        golang.org/x/exp/typeparams@v0.0.0-20231108232855-2478ac86f678 (sum: h1:1P7xPZEwZMoBoz0Yze5Nx2/4pxj6nw9ZqHWXqP0iRgQ=)
        golang.org/x/mod@v0.17.0 (sum: h1:zY54UmvipHiNd+pm+m0x9KhZ9hl1/7QNMyxXbc6ICqA=)
        golang.org/x/sync@v0.7.0 (sum: h1:YsImfSBoP9QPYL0xyKJPq0gcaJdG3rInoqxTWbfQu9M=)
        golang.org/x/tools@v0.21.1-0.20240531212143-b6235391adb3 (sum: h1:SHq4Rl+B7WvyM4XODon1LXtP7gcG49+7Jubt1gWWswY=)
```

```
$ go version
go version go1.22.3 linux/amd64
```

```
$ staticcheck ./...          
panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident

goroutine 6874 [running]:
honnef.co/go/tools/staticcheck/sa1006.run.func1({0xa469f0?, 0xc096492900})
        /home/ldez/sources/dominikh/go-tools/staticcheck/sa1006/sa1006.go:92 +0x792
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc04b78f9c8, {0xc0048dadc8?, 0xd2de20?, 0xc017878660?}, 0xc0048dadb8)
        /home/ldez/sources/go/pkg/mod/golang.org/x/tools@v0.21.1-0.20240531212143-b6235391adb3/go/ast/inspector/inspector.go:82 +0x8f
honnef.co/go/tools/analysis/code.Preorder(...)
        /home/ldez/sources/dominikh/go-tools/analysis/code/visit.go:16
honnef.co/go/tools/staticcheck/sa1006.run(0x8d6700?)
        /home/ldez/sources/dominikh/go-tools/staticcheck/sa1006/sa1006.go:101 +0x88
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0xc0c6323200, {0xa4af18?, 0xc0226ff860})
        /home/ldez/sources/dominikh/go-tools/lintcmd/runner/runner.go:986 +0x71b
honnef.co/go/tools/lintcmd/runner.genericHandle({0xa4af18, 0xc0226ff860}, {0xa4af18?, 0xc0226ff180?}, 0xc08311aae0, 0x0, 0xc0048db308)
        /home/ldez/sources/dominikh/go-tools/lintcmd/runner/runner.go:811 +0x11f
honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers(0xc002638c30, 0xc002522c60, 0xc04b8f00a0)
        /home/ldez/sources/dominikh/go-tools/lintcmd/runner/runner.go:1059 +0x707
honnef.co/go/tools/lintcmd/runner.(*subrunner).doUncached(0xc002638c30, 0xc002522c60)
        /home/ldez/sources/dominikh/go-tools/lintcmd/runner/runner.go:714 +0x189
honnef.co/go/tools/lintcmd/runner.(*subrunner).do(0xc002638c30, {0xa4af60?, 0xc002522c60})
        /home/ldez/sources/dominikh/go-tools/lintcmd/runner/runner.go:571 +0x948
honnef.co/go/tools/lintcmd/runner.(*Runner).Run.func2({0xa4af60?, 0xc002522c60?})
        /home/ldez/sources/dominikh/go-tools/lintcmd/runner/runner.go:1225 +0x2a
honnef.co/go/tools/lintcmd/runner.genericHandle({0xa4af60, 0xc002522c60}, {0xa4af60?, 0xc0015d17a0?}, 0xc001a0ee40, 0xc0003bc310, 0xc032fd2dc0)
        /home/ldez/sources/dominikh/go-tools/lintcmd/runner/runner.go:811 +0x11f
created by honnef.co/go/tools/lintcmd/runner.(*Runner).Run in goroutine 1
        /home/ldez/sources/dominikh/go-tools/lintcmd/runner/runner.go:1224 +0x3d4
```

golangci-lint with staticcheck v0.5.0-0.dev.0.20240621194838-1f707279039d:

```
Panic: SA1006: package \"downwardapi\" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident: goroutine 190569 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/golangci/golangci-lint/pkg/goanalysis.(*action).analyzeSafe.func1()
	github.com/golangci/golangci-lint/pkg/goanalysis/runner_action.go:109 +0x277
panic({0x1842400?, 0xc0a3c2a870?})
	runtime/panic.go:770 +0x132
honnef.co/go/tools/staticcheck/sa1006.run.func1({0x1c9b6a8?, 0xc0a7ea27c0})
	honnef.co/go/tools@v0.5.0-0.dev.0.20240621194838-1f707279039d/staticcheck/sa1006/sa1006.go:92 +0x792
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc077475278, {0xc005996cc8?, 0x25bb300?, 0xc018e38a80?}, 0xc004a37cb8)
	golang.org/x/tools@v0.22.0/go/ast/inspector/inspector.go:82 +0x8f
honnef.co/go/tools/analysis/code.Preorder(...)
	honnef.co/go/tools@v0.5.0-0.dev.0.20240621194838-1f707279039d/analysis/code/visit.go:16
honnef.co/go/tools/staticcheck/sa1006.run(0x1821660?)
	honnef.co/go/tools@v0.5.0-0.dev.0.20240621194838-1f707279039d/staticcheck/sa1006/sa1006.go:101 +0x88
github.com/golangci/golangci-lint/pkg/goanalysis.(*action).analyze(0xc007f72230)
	github.com/golangci/golangci-lint/pkg/goanalysis/runner_action.go:191 +0xa02
github.com/golangci/golangci-lint/pkg/goanalysis.(*action).analyzeSafe.func2()
	github.com/golangci/golangci-lint/pkg/goanalysis/runner_action.go:113 +0x17
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0029a59a0, {0x19b20ad, 0x6}, 0xc005996f48)
	github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/goanalysis.(*action).analyzeSafe(0xc004fde5a0?)
	github.com/golangci/golangci-lint/pkg/goanalysis/runner_action.go:112 +0x7a
github.com/golangci/golangci-lint/pkg/goanalysis.(*loadingPackage).analyze.func2(0xc007f72230)
	github.com/golangci/golangci-lint/pkg/goanalysis/runner_loadingpackage.go:80 +0xa8
created by github.com/golangci/golangci-lint/pkg/goanalysis.(*loadingPackage).analyze in goroutine 1959
	github.com/golangci/golangci-lint/pkg/goanalysis/runner_loadingpackage.go:75 +0x205
```

**Comment by dominikh** [comment]
Thanks for the report.
