### ISSUE TITLE
panic: Cannot range over: func(yield func(K, V) bool) with Go 1.23

### ISSUE THREAD

**Issue by kevinburke** [dominikh/go-tools#1576]
If you don't care about 1.23 compile errors at this point - no worries.

go version: go version devel go1.23-7d19d508a9 Wed Jul 3 19:02:39 2024 +0000 darwin/arm64
go env:

```
GO111MODULE='off'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/kburke/Library/Caches/go-build'
GOENV='/Users/kburke/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/kburke/pkg/mod'
GONOPROXY='github.com/segmentio'
GONOSUMDB='github.com/segmentio'
GOOS='darwin'
GOPATH='/Users/kburke'
GOPRIVATE='github.com/segmentio'
GOPROXY='direct'
GOROOT='/Users/kburke/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/kburke/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='devel go1.23-7d19d508a9 Wed Jul 3 19:02:39 2024 +0000'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/kburke/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD=''
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/9s/w0d5_1fx71j5f225g95vtx340000gn/T/go-build3997072116=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

To reproduce: check out github.com/kevinburke/twilio-go, and then run:

```
 $ GO111MODULE=on go run honnef.co/go/tools/cmd/staticcheck@latest ./...
panic: Cannot range over: func(yield func(K, V) bool)

goroutine 241 [running]:
honnef.co/go/tools/go/ir.(*builder).rangeStmt(0x14000573a30, 0x14000699a40, 0x140009103c0, 0x0, {0x1013c7870, 0x140009103c0})
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2225 +0x6dc
honnef.co/go/tools/go/ir.(*builder).stmt(0x14000573a30, 0x14000699a40, {0x1013c9bd8?, 0x140009103c0?})
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2438 +0x1c0
honnef.co/go/tools/go/ir.(*builder).stmtList(...)
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:859
honnef.co/go/tools/go/ir.(*builder).stmt(0x14000573a30, 0x14000699a40, {0x1013c9818?, 0x14000990a20?})
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2396 +0x10c4
honnef.co/go/tools/go/ir.(*builder).buildFunction(0x14000573a30, 0x14000699a40)
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2508 +0x368
honnef.co/go/tools/go/ir.(*builder).buildFuncDecl(0x14000573a30, 0x1400019b050, 0x14000990a50)
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2545 +0x1a4
honnef.co/go/tools/go/ir.(*Package).build(0x1400019b050)
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2649 +0x934
sync.(*Once).doSlow(0x140001520e0?, 0x14000789f20?)
	/Users/kburke/go/src/sync/once.go:76 +0xf8
sync.(*Once).Do(...)
	/Users/kburke/go/src/sync/once.go:67
honnef.co/go/tools/go/ir.(*Package).Build(...)
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2567
honnef.co/go/tools/internal/passes/buildir.run(0x14000912000)
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/internal/passes/buildir/buildir.go:86 +0x134
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0x140004ab4a0, {0x1013cc338?, 0x14000367220})
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:992 +0x600
honnef.co/go/tools/lintcmd/runner.genericHandle({0x1013cc338, 0x14000367220}, {0x1013cc338?, 0x14000367180?}, 0x1400028a2a0, 0x140003c65a0, 0x1400091aab0)
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:817 +0x10c
created by honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers in goroutine 227
	/Users/kburke/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:1061 +0x568
```

I don't know where more specifically the error is to be found.

**Comment by dominikh** [comment]
You will want to use the `2024.1rc1` pre-release, not `latest`, which resolves to 2023.1.7.
