### ISSUE TITLE
panic: `internal error: 1: expected 'package', found i`

### ISSUE THREAD

**Issue by qarmin** [dominikh/go-tools#1582]
File content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
//line :1
i
```

command
```
timeout -v 100 staticcheck -checks ALL TEST___FILE.go
```

cause this
```
panic: internal error: 1: expected 'package', found i

goroutine 1 [running]:
honnef.co/go/tools/lintcmd.failed({0xc0000cc780, {{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...})
	/home/runner/work/Automated-Fuzzer/Automated-Fuzzer/gotools/lintcmd/lint.go:459 +0x734
honnef.co/go/tools/lintcmd.(*linter).lint(0xc0000000c0, 0xc000412000, 0xc00003f798, {0xc0002360b0, 0x1, 0x1})
	/home/runner/work/Automated-Fuzzer/Automated-Fuzzer/gotools/lintcmd/lint.go:188 +0x978
honnef.co/go/tools/lintcmd.(*linter).run(0xc0000000c0, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}})
	/home/runner/work/Automated-Fuzzer/Automated-Fuzzer/gotools/lintcmd/lint.go:150 +0x48d
honnef.co/go/tools/lintcmd.(*Command).lint(0xc0000d6480)
	/home/runner/work/Automated-Fuzzer/Automated-Fuzzer/gotools/lintcmd/cmd.go:499 +0xa05
honnef.co/go/tools/lintcmd.(*Command).Run(0xc0000d6480)
	/home/runner/work/Automated-Fuzzer/Automated-Fuzzer/gotools/lintcmd/cmd.go:316 +0x314
main.main()
	/home/runner/work/Automated-Fuzzer/Automated-Fuzzer/gotools/cmd/staticcheck/staticcheck.go:44 +0x4ea

##### Automatic Fuzzer note, output status "Some(2)", output signal "None"
```

[compressed.zip](https://github.com/user-attachments/files/16505322/compressed.zip)

**Comment by dominikh** [comment]
Thanks.
