### ISSUE TITLE
staticcheck internal error - malformed position

### ISSUE THREAD

**Issue by Shikkic** [dominikh/go-tools#387]
I came across a recent issue running `staticcheck`. We'll typically run `staticcheck` over all packages in a directory via:

```sh
$ staticcheck $(go list ./... | grep -v vendor/)
```

However at some point I guess we updated to a new version and now I'm seeing a panic over some tmp packages generated by `staticcheck`

```sh
panic: internal error: malformed position "/tmp/gopackages280076669/go-build/net/cgo_linux.cgo1.go:1"

goroutine 1 [running]:
honnef.co/go/tools/lint/lintutil.parsePos(0xc42428af00, 0x39, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/honnef.co/go/tools/lint/lintutil/util.go:320 +0x331
honnef.co/go/tools/lint/lintutil.compileErrors(0xc42018eb60, 0x0, 0x0, 0x0)
	/go/src/honnef.co/go/tools/lint/lintutil/util.go:347 +0x134
honnef.co/go/tools/lint/lintutil.compileErrors(0xc4200aea80, 0x0, 0x0, 0x0)
	/go/src/honnef.co/go/tools/lint/lintutil/util.go:340 +0x456
honnef.co/go/tools/lint/lintutil.compileErrors(0xc420442ee0, 0xc420191f50, 0xc42054edf0, 0x0)
	/go/src/honnef.co/go/tools/lint/lintutil/util.go:340 +0x456
honnef.co/go/tools/lint/lintutil.compileErrors(0xc420118e00, 0x0, 0x0, 0x0)
	/go/src/honnef.co/go/tools/lint/lintutil/util.go:340 +0x456
honnef.co/go/tools/lint/lintutil.compileErrors(0xc42031aee0, 0xc4200cab70, 0xc42054f1d0, 0x0)
	/go/src/honnef.co/go/tools/lint/lintutil/util.go:340 +0x456
honnef.co/go/tools/lint/lintutil.compileErrors(0xc420447960, 0x0, 0x0, 0x0)
	/go/src/honnef.co/go/tools/lint/lintutil/util.go:340 +0x456
honnef.co/go/tools/lint/lintutil.compileErrors(0xc420394e00, 0xc420191620, 0xc42054f5b0, 0x0)
	/go/src/honnef.co/go/tools/lint/lintutil/util.go:340 +0x456
honnef.co/go/tools/lint/lintutil.compileErrors(0xc4202308c0, 0x0, 0xc, 0xc434c3f5c0)
	/go/src/honnef.co/go/tools/lint/lintutil/util.go:340 +0x456
honnef.co/go/tools/lint/lintutil.Lint(0xc420058720, 0x4, 0x6, 0xc420010080, 0x6, 0x6, 0xc42054fe00, 0x90bd60, 0xc420016a88, 0x0, ...)
	/go/src/honnef.co/go/tools/lint/lintutil/util.go:287 +0x4d7
honnef.co/go/tools/lint/lintutil.ProcessFlagSet(0xc420058720, 0x4, 0x6, 0xc4200586c0)
	/go/src/honnef.co/go/tools/lint/lintutil/util.go:178 +0x9b8
main.main()
	/go/src/honnef.co/go/tools/cmd/staticcheck/staticcheck.go:29 +0x35e
```

> NOTE: Not sure if it matters be the commands are being executed inside of a container.

Anyone else seeing this issue?

**Comment by dominikh** [comment]
Which version of Go are you using (when running staticcheck)?

**Comment by dominikh** [comment]
This should be fixed in master, and will be part of the upcoming 2019.1.1 release.

**Comment by Shikkic** [comment]
I'm using 1.9.7-alpine if it still matters.

Oh awesome. Thanks @dominikh!

**Comment by dominikh** [comment]
@Shikkic It matters to the extent that I can tell you that the latest release only supports Go 1.10 and Go 1.11 – or, in general, the last two releases of Go.
