### ISSUE TITLE
unused: the new unused seems broken when "-exported=true" is used

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#443]
`pkg/pkg.go`:

```go
package pkg

const A = "a"
```

`main.go`:

```go
package main

import (
	"fmt"

	"pkg"
)

func main() {
	fmt.Println(pkg.A)
}
```

```sh
$ unused -exported=true ./...
Unused has been deprecated. Please use staticcheck instead.
pkg/pkg.go:3:7: const A is unused (U1000) 
```

* * *

Shell reproducer:

```sh
#!/usr/bin/env sh

mkdir pkg
printf "package pkg\n\nconst A = \"a\"" > pkg/pkg.go
printf "package main\n\nimport (\"fmt\"; \"./pkg\")\n\n" > main.go
printf "func main() {\n\tfmt.Println(pkg.A)\n}" >> main.go
go fmt main.go && go run main.go && unused -exported=true ./...
```

**Comment by ainar-g** [comment]
@dominikh It actually got worse.

```sh
$ sh foo.sh 
main.go
a
Unused has been deprecated. Please use staticcheck instead.
panic: failed assertion

goroutine 382 [running]:
honnef.co/go/tools/unused.assert(...)
	/home/ainar/go/src/honnef.co/go/tools/unused/unused.go:129
honnef.co/go/tools/unused.(*Graph).use(0xc009acf050, 0x765100, 0xc00283d0e0, 0x72a980, 0xc0030438a0, 0x77c3f4, 0xd)
	/home/ainar/go/src/honnef.co/go/tools/unused/unused.go:877 +0x516
honnef.co/go/tools/unused.(*Graph).seeAndUse(0xc009acf050, 0x765100, 0xc00283d0e0, 0x72a980, 0xc0030438a0, 0x77c3f4, 0xd)
	/home/ainar/go/src/honnef.co/go/tools/unused/unused.go:889 +0x8d
honnef.co/go/tools/unused.(*Graph).typ(0xc009acf050, 0x7efce0, 0xc0030438a0)
	/home/ainar/go/src/honnef.co/go/tools/unused/unused.go:1403 +0x26b
honnef.co/go/tools/unused.(*Graph).instructions(0xc009acf050, 0xc001ca5400)
	/home/ainar/go/src/honnef.co/go/tools/unused/unused.go:1474 +0x1857
honnef.co/go/tools/unused.(*Graph).function(0xc009acf050, 0xc001ca5400)
	/home/ainar/go/src/honnef.co/go/tools/unused/unused.go:1254 +0x124
honnef.co/go/tools/unused.(*Graph).entry(0xc009acf050, 0xc009bd8500)
	/home/ainar/go/src/honnef.co/go/tools/unused/unused.go:1167 +0xb43
honnef.co/go/tools/unused.(*Checker).Check.func1(0xc009bdb940, 0x2, 0x2)
	/home/ainar/go/src/honnef.co/go/tools/unused/unused.go:454 +0x1ca
honnef.co/go/tools/unused.(*Checker).Check(0xc00000c480, 0xc009adce40, 0xc009bc4a80, 0x0, 0x63a6e8, 0xc000056cc0)
	/home/ainar/go/src/honnef.co/go/tools/unused/unused.go:660 +0x5df
honnef.co/go/tools/unused.(*Checker).Lint(0xc00000c480, 0xc009bc4a80)
	/home/ainar/go/src/honnef.co/go/tools/unused/unused.go:409 +0x55
honnef.co/go/tools/lint.(*Linter).Lint.func1(0xc0060bab50, 0xc001105740, 0xc009bc4a80)
	/home/ainar/go/src/honnef.co/go/tools/lint/lint.go:465 +0xd8
created by honnef.co/go/tools/lint.(*Linter).Lint
	/home/ainar/go/src/honnef.co/go/tools/lint/lint.go:456 +0x1e4a
```

**Comment by dominikh** [comment]
Sigh, of course. Give me a minute (to reflect on why I shouldn't just toss out whole program mode ;)) to fix it properly.

**Comment by dominikh** [comment]
5f558939d3aafbdade56e68e14c4f6b4c2df786e should be the correct fix for this. Sorry for the inconvenience.
