### ISSUE TITLE
panic: unexpected Object type: builtin unsafe.Alignof

### ISSUE THREAD

**Issue by y0ssar1an** [dominikh/go-tools#49]
```
panic: unexpected Object type: builtin unsafe.Alignof

goroutine 1 [running]:
honnef.co/go/tools/ssa.memberFromObject(0xc4267e7260, 0x1745b00, 0xc4200c12c0, 0x0, 0x0)
	/Users/ryan/go/src/honnef.co/go/tools/ssa/create.go:103 +0x4c2
honnef.co/go/tools/ssa.(*Program).CreatePackage(0xc4265f9d60, 0xc4200c02d0, 0x0, 0x0, 0x0, 0xc420440250, 0x1, 0xc4267e7200)
	/Users/ryan/go/src/honnef.co/go/tools/ssa/create.go:196 +0x7bb
honnef.co/go/tools/ssa/ssautil.CreateProgram(0xc420014a00, 0x40, 0x127d3f6)
	/Users/ryan/go/src/honnef.co/go/tools/ssa/ssautil/load.go:34 +0x31a
honnef.co/go/tools/lint.(*Linter).Lint(0xc4267df830, 0xc420014a00, 0x0)
	/Users/ryan/go/src/honnef.co/go/tools/lint/lint.go:110 +0x4c
honnef.co/go/tools/lint/lintutil.(*runner).lint(0xc4200165a0, 0xc420014a00, 0x0)
	/Users/ryan/go/src/honnef.co/go/tools/lint/lintutil/util.go:199 +0x95
honnef.co/go/tools/lint/lintutil.ProcessFlagSet(0x1528f87, 0xb, 0x173d6a0, 0xc420152b80, 0xc42001e240)
	/Users/ryan/go/src/honnef.co/go/tools/lint/lintutil/util.go:148 +0x761
honnef.co/go/tools/lint/lintutil.ProcessArgs(0x1528f87, 0xb, 0x173d6a0, 0xc420152b80, 0xc4200190d0, 0x1, 0x1)
	/Users/ryan/go/src/honnef.co/go/tools/lint/lintutil/util.go:191 +0xa0
main.main()
	/Users/ryan/go/src/honnef.co/go/tools/cmd/staticcheck/staticcheck.go:21 +0x283
```
I started getting this panic with every repo I've tried to scan. Scans yesterday succeeded, but today every repo panics. I see the last commit was Feb 27th, 2017, so I'm baffled. `gosimple` and `unused` are also panicking.

**Comment by glerchundi** [comment]
Same here!

**Comment by y0ssar1an** [comment]
Thank you very much for the quick fix! 🙏
