### ISSUE TITLE
Segmentation violation when running static check

### ISSUE THREAD

**Issue by replay** [dominikh/go-tools#636]
With the latest commit c62cfd4e319fb4b628edfef62ca6818a4e24e542 I'm getting a segmentation violation when running `staticcheck`. A similar issue seems to have been fixed 18 days ago with a2fc4037bf9fb9a7662bf915cde585ccc17c1c2b and when i use that commit it don't get the segmentation violation, but it looks as if this has been reintroduced recently (i think in ffc5b11a1d02d52fc20fc2b88d339f5f59773131).

This is what I'm running, together with the resulting output (in the repo https://github.com/grafana/metrictank):
```
replay@mst-nb:~/go/src/github.com/grafana/metrictank$ staticcheck -checks U1000 ./...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6da988]

goroutine 1442 [running]:
honnef.co/go/tools/ir.addEdge(...)
        /home/replay/go/src/honnef.co/go/tools/ir/func.go:24
honnef.co/go/tools/ir.emitJump(0xc01a080a00, 0x0, 0xc006075630)
        /home/replay/go/src/honnef.co/go/tools/ir/emit.go:279 +0x118
honnef.co/go/tools/ir.(*builder).stmt(0xc01a179668, 0xc01a080a00, 0xb9cea0, 0xc00d657240)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2213 +0x590
honnef.co/go/tools/ir.(*builder).stmtList(0xc01a179668, 0xc01a080a00, 0xc005625cc0, 0x1, 0x1)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:775 +0x72
honnef.co/go/tools/ir.(*builder).typeSwitchStmt(0xc01a179668, 0xc01a080a00, 0xc00db3b8c0, 0x0)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:1545 +0x1d62
honnef.co/go/tools/ir.(*builder).stmt(0xc01a179668, 0xc01a080a00, 0xb9d820, 0xc00db3b8c0)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2248 +0x4de
honnef.co/go/tools/ir.(*builder).stmtList(0xc01a179668, 0xc01a080a00, 0xc005625ce0, 0x1, 0x1)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:775 +0x72
honnef.co/go/tools/ir.(*builder).stmt(0xc01a179668, 0xc01a080a00, 0xb9ce60, 0xc00db3b920)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2218 +0x22bd
honnef.co/go/tools/ir.(*builder).rangeStmt(0xc01a179668, 0xc01a080a00, 0xc006075180, 0x0)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2077 +0x439
honnef.co/go/tools/ir.(*builder).stmt(0xc01a179668, 0xc01a080a00, 0xb9d560, 0xc006075180)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2260 +0x18f6
honnef.co/go/tools/ir.(*builder).stmtList(0xc01a179668, 0xc01a080a00, 0xc007dc4340, 0x4, 0x4)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:775 +0x72
honnef.co/go/tools/ir.(*builder).stmt(0xc01a179668, 0xc01a080a00, 0xb9ce60, 0xc00db3bb00)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2218 +0x22bd
honnef.co/go/tools/ir.(*builder).stmt(0xc01a179668, 0xc01a080a00, 0xb9d320, 0xc007dc4500)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2233 +0x2879
honnef.co/go/tools/ir.(*builder).stmtList(0xc01a179668, 0xc01a080a00, 0xc005625de0, 0x1, 0x1)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:775 +0x72
honnef.co/go/tools/ir.(*builder).typeSwitchStmt(0xc01a179668, 0xc01a080a00, 0xc00159f050, 0xc01b872b80)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:1545 +0x1d62
honnef.co/go/tools/ir.(*builder).stmt(0xc01a179668, 0xc01a080a00, 0xb9d4a0, 0xc00f43fca0)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2248 +0x4de
honnef.co/go/tools/ir.(*builder).stmtList(0xc01a179668, 0xc01a080a00, 0xc00264b080, 0x7, 0x8)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:775 +0x72
honnef.co/go/tools/ir.(*builder).stmt(0xc01a179668, 0xc01a080a00, 0xb9ce60, 0xc00159f0e0)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2218 +0x22bd
honnef.co/go/tools/ir.(*builder).buildFunction(0xc01a179668, 0xc01a080a00)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2327 +0x37e
honnef.co/go/tools/ir.(*builder).buildFuncDecl(0xc01a179668, 0xc00da93290, 0xc00159f140)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2362 +0xed
honnef.co/go/tools/ir.(*Package).build(0xc00da93290)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2468 +0xcb9
sync.(*Once).Do(0xc00da932e8, 0xc00e591780)
        /usr/local/go/src/sync/once.go:44 +0xb3
honnef.co/go/tools/ir.(*Package).Build(0xc00da93290)
        /home/replay/go/src/honnef.co/go/tools/ir/builder.go:2386 +0x54
honnef.co/go/tools/internal/passes/buildir.run(0xc0111fabe0, 0x778642b1, 0xfb3b20, 0xc0000aa240, 0xc002e67c48)
        /home/replay/go/src/honnef.co/go/tools/internal/passes/buildir/buildir.go:89 +0x2a4
honnef.co/go/tools/lint.(*Runner).runAnalysisUser(0xc00013d6c0, 0xc0111fabe0, 0xc00d3c89b0, 0xc00d8c09f0, 0xc000728c68, 0x1, 0x1)
        /home/replay/go/src/honnef.co/go/tools/lint/runner.go:487 +0x2aa
honnef.co/go/tools/lint.(*Runner).runAnalysis(0xc00013d6c0, 0xc00d3c89b0, 0x0, 0x0, 0x0, 0x0)
        /home/replay/go/src/honnef.co/go/tools/lint/runner.go:367 +0x4cb
honnef.co/go/tools/lint.(*Runner).runAnalysisUser(0xc00013d6c0, 0xc0111faaa0, 0xc00d3c86e0, 0xc00d8c0960, 0xc000510f58, 0xc000510ee0, 0x42d64d)
        /home/replay/go/src/honnef.co/go/tools/lint/runner.go:473 +0xe8
honnef.co/go/tools/lint.(*Runner).runAnalysis(0xc00013d6c0, 0xc00d3c86e0, 0x0, 0x0, 0x0, 0x0)
        /home/replay/go/src/honnef.co/go/tools/lint/runner.go:367 +0x4cb
honnef.co/go/tools/lint.(*Runner).processPkg.func3(0xc00a215650, 0xc000292c60, 0xc000199a00, 0xc00013d6c0, 0xc00d3c86e0, 0xc00d8c86c0, 0x6, 0x6, 0x0)
        /home/replay/go/src/honnef.co/go/tools/lint/runner.go:906 +0x75
created by honnef.co/go/tools/lint.(*Runner).processPkg
        /home/replay/go/src/honnef.co/go/tools/lint/runner.go:901 +0xa52
```
This is my env:
```
replay@mst-nb:~/go/src/honnef.co/go/tools/cmd/staticcheck$ ./staticcheck -version
staticcheck (no version)

replay@mst-nb:~/go/src/github.com/grafana/metrictank$ staticcheck -debug.version
staticcheck (no version)

Compiled with Go version: go1.12.5
Built without Go modules

replay@mst-nb:~/go/src/github.com/grafana/metrictank$ go version
go version go1.12.5 linux/amd64

replay@mst-nb:~/go/src/github.com/grafana/metrictank$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/replay/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/replay/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build124508773=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by dominikh** [comment]
Can reproduce, will fix. (Note that the panic fixed in a2fc403 and the panic introduced in ffc5b11 are independent of each other.)
