### ISSUE TITLE
staticcheck: SA4016: panic when constant has been dot-imported 

### ISSUE THREAD

**Issue by buglloc** [dominikh/go-tools#719]
- The output of 'staticcheck -version':
```
$ staticcheck --version
staticcheck 2020.1.3
```
- The output of 'staticcheck -debug.version':
```
$ staticcheck -debug.version
staticcheck 2020.1.3

Compiled with Go version: go1.14.1
Main module:
        honnef.co/go/tools
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/tools@v0.0.0-20191130070609-6e064ea0cf2d (sum: h1:/iIZNFGxc/a7C3yWjGcnboV+Tkc7mxr+p6fDztwoxuM=)
```
- The output of 'go version':
```
$ go version
go version go1.14.1 linux/amd64
```
- The output of 'go env':
```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/buglloc/.cache/go-build"
GOENV="/home/buglloc/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/buglloc/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build975043831=/tmp/go-build -gno-record-gcc-switches"
```
- Minimum reproducer: https://github.com/buglloc/sa4016
- Real life example: https://github.com/gogo/protobuf/blob/5628607bb4c51c3157aacc3a50f0ab707582b805/proto/all_test.go#L1540
- Problem:
```
$ staticcheck --checks="SA4016" github.com/buglloc/sa4016/...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x50adc2]

goroutine 88 [running]:
go/ast.(*File).End(0x0, 0x200)
        /usr/lib/go/src/go/ast/ast.go:1000 +0x22
golang.org/x/tools/go/ast/astutil.PathEnclosingInterval(0x0, 0x17, 0x17, 0x0, 0x0, 0x0, 0x0)
        /home/buglloc/go/pkg/mod/golang.org/x/tools@v0.0.0-20191130070609-6e064ea0cf2d/go/ast/astutil/enclosing.go:140 +0xd1
honnef.co/go/tools/staticcheck.CheckSillyBitwiseOps.func1(0xba5020, 0xc000cf74d0)
        /home/buglloc/go/src/honnef.co/go/tools/staticcheck/lint.go:2713 +0x1db
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc000d091e0, 0xc00059dbd8, 0x1, 0x1, 0xc00059dbe8)
        /home/buglloc/go/pkg/mod/golang.org/x/tools@v0.0.0-20191130070609-6e064ea0cf2d/go/ast/inspector/inspector.go:77 +0x9f
honnef.co/go/tools/code.Preorder(...)
        /home/buglloc/go/src/honnef.co/go/tools/code/code.go:480
honnef.co/go/tools/staticcheck.CheckSillyBitwiseOps(0xc0000f28c0, 0x8669214, 0xfa40c0, 0xc000321e68, 0x0)
        /home/buglloc/go/src/honnef.co/go/tools/staticcheck/lint.go:2754 +0xc5
honnef.co/go/tools/lint.(*Runner).runAnalysisUser(0xc000278b00, 0xc0000f28c0, 0xc0003530e0, 0x0, 0x0, 0x0, 0x0)
        /home/buglloc/go/src/honnef.co/go/tools/lint/runner.go:494 +0x2af
honnef.co/go/tools/lint.(*Runner).runAnalysis(0xc000278b00, 0xc0003530e0, 0x0, 0x0, 0x0, 0x0)
        /home/buglloc/go/src/honnef.co/go/tools/lint/runner.go:374 +0x574
honnef.co/go/tools/lint.(*Runner).processPkg.func3(0xc0012b1bf0, 0xc0001d1d40, 0xc000256820, 0xc000278b00, 0xc0003530e0, 0xc000314230, 0x7, 0x7, 0x0)
        /home/buglloc/go/src/honnef.co/go/tools/lint/runner.go:913 +0x79
created by honnef.co/go/tools/lint.(*Runner).processPkg
        /home/buglloc/go/src/honnef.co/go/tools/lint/runner.go:908 +0x9f3
```

**Comment by dominikh** [comment]
Thanks for the concise reproducer. Will fix.

**Comment by buglloc** [comment]
Wow! So quickly, thanks :)
