### ISSUE TITLE
simple + Go tip: Program.CreatePackage("unsafe") was not called

### ISSUE THREAD

**Issue by gyuho** [dominikh/go-tools#76]
Hope this is not a duplicate issue.

```
panic: Package("runtime/cgo").Build(): unsatisfied import: Program.CreatePackage("unsafe") was not called
goroutine 2679 [running]:
honnef.co/go/tools/ssa.(*Package).build(0xc449b07e60)
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2300 +0x10f9
honnef.co/go/tools/ssa.(*Package).(honnef.co/go/tools/ssa.build)-fm()
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2260 +0x2a
sync.(*Once).Do(0xc449b07e8c, 0xc44a92bf98)
	/home/travis/.gimme/versions/go/src/sync/once.go:44 +0xbe
honnef.co/go/tools/ssa.(*Package).Build(0xc449b07e60)
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2260 +0x4c
honnef.co/go/tools/ssa.(*Program).Build.func1(0xc44a86c0c0, 0xc449b07e60)
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2244 +0x2b
created by honnef.co/go/tools/ssa.(*Program).Build
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2243 +0x118: No such file or directory
gosimple warning:
panic: Package("runtime/cgo").Build(): unsatisfied import: Program.CreatePackage("unsafe") was not called
goroutine 2679 [running]:
honnef.co/go/tools/ssa.(*Package).build(0xc449b07e60)
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2300 +0x10f9
honnef.co/go/tools/ssa.(*Package).(honnef.co/go/tools/ssa.build)-fm()
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2260 +0x2a
sync.(*Once).Do(0xc449b07e8c, 0xc44a92bf98)
	/home/travis/.gimme/versions/go/src/sync/once.go:44 +0xbe
honnef.co/go/tools/ssa.(*Package).Build(0xc449b07e60)
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2260 +0x4c
honnef.co/go/tools/ssa.(*Program).Build.func1(0xc44a86c0c0, 0xc449b07e60)
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2244 +0x2b
created by honnef.co/go/tools/ssa.(*Program).Build
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2243 +0x118
Checking unused...
unused checking failed:
panic: Package("runtime/cgo").Build(): unsatisfied import: Program.CreatePackage("unsafe") was not called
goroutine 2455 [running]:
honnef.co/go/tools/ssa.(*Package).build(0xc435d23140)
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2300 +0x10f9
honnef.co/go/tools/ssa.(*Package).(honnef.co/go/tools/ssa.build)-fm()
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2260 +0x2a
sync.(*Once).Do(0xc435d2316c, 0xc431447f98)
	/home/travis/.gimme/versions/go/src/sync/once.go:44 +0xbe
honnef.co/go/tools/ssa.(*Package).Build(0xc435d23140)
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2260 +0x4c
honnef.co/go/tools/ssa.(*Program).Build.func1(0xc4292218c0, 0xc435d23140)
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2244 +0x2b
created by honnef.co/go/tools/ssa.(*Program).Build
	/home/travis/gopath/src/honnef.co/go/tools/ssa/builder.go:2243 +0x118
```

Full logs can be found at https://travis-ci.org/coreos/etcd/jobs/213502335#L604.

Thanks!

**Comment by mvdan** [comment]
What version of go-tools is this on?

**Comment by gyuho** [comment]
@mvdan We always use tip with `go get`

https://github.com/coreos/etcd/blob/master/.travis.yml#L45-L47

**Comment by dominikh** [comment]
IIRC this is caused by an outdated copy of x/tools/go/loader.

**Comment by mvdan** [comment]
@gyuho try adding `-u` in those lines

**Comment by gyuho** [comment]
Worked. Thanks @mvdan and @dominikh !
