### ISSUE TITLE
staticcheck: segmentation fault

### ISSUE THREAD

**Issue by henrikhodne** [dominikh/go-tools#82]
Somehow I've gotten `staticcheck` to segfault when I run it:

```
% staticcheck ./... | grep -v vendor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4ebfc2]
goroutine 59801 [running]:
go/ast.(*File).End(0x0, 0x0)
        /usr/lib/go/src/go/ast/ast.go:982 +0x22
golang.org/x/tools/go/ast/astutil.PathEnclosingInterval(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1)
        /home/henrik/go/src/golang.org/x/tools/go/ast/astutil/enclosing.go:140 +0x136
honnef.co/go/tools/staticcheck.(*Checker).CheckSillyBitwiseOps(0xc420140d00, 0xc453a3aba0)
        /home/henrik/go/src/honnef.co/go/tools/staticcheck/lint.go:2233 +0x2ee
honnef.co/go/tools/staticcheck.(*Checker).CheckSillyBitwiseOps-fm(0xc453a3aba0)
        /home/henrik/go/src/honnef.co/go/tools/staticcheck/lint.go:244 +0x34
honnef.co/go/tools/lint.(*Linter).Lint.func1(0xc44dbab070, 0xc453a3a0f0, 0xc453a3aba0)
        /home/henrik/go/src/honnef.co/go/tools/lint/lint.go:236 +0x93
created by honnef.co/go/tools/lint.(*Linter).Lint
        /home/henrik/go/src/honnef.co/go/tools/lint/lint.go:237 +0x16c7
```

After some poking, it looks like `golang.org/x/sys/unix` is the cause (it's in my vendor directory):

```
% staticcheck golang.org/x/sys/unix
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4ebfc2]
goroutine 9472 [running]:
go/ast.(*File).End(0x0, 0x0)
        /usr/lib/go/src/go/ast/ast.go:982 +0x22
golang.org/x/tools/go/ast/astutil.PathEnclosingInterval(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9)
        /home/henrik/go/src/golang.org/x/tools/go/ast/astutil/enclosing.go:140 +0x136
honnef.co/go/tools/staticcheck.(*Checker).CheckSillyBitwiseOps(0xc420140820, 0xc424cc0d80)
        /home/henrik/go/src/honnef.co/go/tools/staticcheck/lint.go:2233 +0x2ee
honnef.co/go/tools/staticcheck.(*Checker).CheckSillyBitwiseOps-fm(0xc424cc0d80)
        /home/henrik/go/src/honnef.co/go/tools/staticcheck/lint.go:244 +0x34
honnef.co/go/tools/lint.(*Linter).Lint.func1(0xc421f67c20, 0xc424cc03f0, 0xc424cc0d80)
        /home/henrik/go/src/honnef.co/go/tools/lint/lint.go:236 +0x93
created by honnef.co/go/tools/lint.(*Linter).Lint
        /home/henrik/go/src/honnef.co/go/tools/lint/lint.go:237 +0x16c7
```

The revision I have of golang.org/x/sys/unix is golang/sys@7a6e5648d140666db5d920909e082ca00a87ba2c.

**Comment by dominikh** [comment]
I can reproduce the issue and have roughly figured out why it happens. I'll try and fix the issue over the weekend.
