### ISSUE TITLE
staticcheck: panic

### ISSUE THREAD

**Issue by Vemmy124** [dominikh/go-tools#873]
There is generally a panic

- The output of 'staticcheck -version'
`staticcheck 2020.1.5 (2020.1.6 still fails)`

- The output of 'staticcheck -debug.version' (it is fine if this command fails)
```
Compiled with Go version: go1.15.2
Main module:
        honnef.co/go/tools@v0.0.1-2020.1.5 (sum: h1:nI5egYTGJakVyOryqLs1cQO5dO0ksin5XXs2pspk75k=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
        golang.org/x/tools@v0.0.0-20200822203824-307de81be3f4 (sum: h1:r0nbB2EeRbGpnVeqxlkgiBpNi/bednpSg78qzZGOuv0=)
        golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
```
- The output of 'go version'
`go version go1.15.2 darwin/amd64`
- The output of 'go env'

- Exactly which command you ran
`staticcheck run ./...`
- Output of the command and what's wrong with the output
```
panic: runtime error: index out of range [0] with length 0

goroutine 34526 [running]:
honnef.co/go/tools/staticcheck.checkCalls.func1(0xc00b4265a0, 0x15c38a0, 0xc00b43cfc0, 0xc00929b680)
        /Users/pkositsyn/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.5/staticcheck/lint.go:2994 +0x855
honnef.co/go/tools/staticcheck.eachCall(0xc00b4265a0, 0xc000c65b88)
        /Users/pkositsyn/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.5/staticcheck/lint.go:2370 +0x148
honnef.co/go/tools/staticcheck.checkCalls(0xc00a858b40, 0xc000199860, 0x10bd726, 0x5fae57dc, 0x2216ca98, 0x161dd8e16356d)
        /Users/pkositsyn/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.5/staticcheck/lint.go:3005 +0xc5
honnef.co/go/tools/staticcheck.callChecker.func1(0xc00a858b40, 0x1897530ee, 0x1813a80, 0xc00b54d718, 0x0)
        /Users/pkositsyn/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.5/staticcheck/lint.go:2950 +0x34
honnef.co/go/tools/lint.(*Runner).runAnalysisUser(0xc00020af80, 0xc00a858b40, 0xc008a9e6e0, 0x0, 0x0, 0xc0025c72a8, 0x4)
        /Users/pkositsyn/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.5/lint/runner.go:494 +0x2c3
honnef.co/go/tools/lint.(*Runner).runAnalysis(0xc00020af80, 0xc008a9e6e0, 0x0, 0x0, 0x0, 0x0)
        /Users/pkositsyn/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.5/lint/runner.go:374 +0x5a5
honnef.co/go/tools/lint.(*Runner).processPkg.func3(0xc004f77a90, 0xc00023e900, 0xc0002d89c0, 0xc00020af80, 0xc008a9e6e0, 0xc006da3600, 0x88, 0x88, 0x3b)
        /Users/pkositsyn/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.5/lint/runner.go:913 +0x79
created by honnef.co/go/tools/lint.(*Runner).processPkg
        /Users/pkositsyn/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.5/lint/runner.go:908 +0x9ff
```

**Comment by Vemmy124** [comment]
In the current version this line fails 
https://github.com/dominikh/go-tools/blob/a6ed285e57c7d3a0fb2922170942f39c5cd6eadb/staticcheck/lint.go#L3028

**Comment by dominikh** [comment]
What code are you running staticcheck on? Is it publicly available?

**Comment by Vemmy124** [comment]
No, it is private unfortunately for the issue

**Comment by dominikh** [comment]
That makes this hard to debug for me. The same check has run on millions of lines of code without crashing, so there's likely something interesting about your code.

Would you be able to run a patched version of 2020.1.5 with the following change, and at least share the specific code it chokes on? You can contact me in private, too, if that makes it easier to share the code.

```
diff --git i/staticcheck/lint.go w/staticcheck/lint.go
index 22b6bbc..a13fcb3 100644
--- i/staticcheck/lint.go
+++ w/staticcheck/lint.go
@@ -2991,6 +2991,9 @@ func checkCalls(pass *analysis.Pass, rules map[string]CallCheck) (interface{}, e
                for idx, arg := range call.Args {
                        for _, e := range arg.invalids {
                                if astcall != nil {
+                                       if idx >= len(astcall.Args) {
+                                               panic(fmt.Sprintf("AST call with too few arguments (%d, %d) at %s", len(astcall.Args), idx, pass.Fset.PositionFor(astcall.Pos(), false)))
+                                       }
                                        report.Report(pass, astcall.Args[idx], e)
                                } else {
                                        report.Report(pass, site, e)
```

**Comment by Vemmy124** [comment]
@dominikh Sure, thanks for the debug snippet.
I could get the minimal piece of code, on which the panic still exists.
https://play.golang.org/p/pflQqHC51Bw

**Comment by dominikh** [comment]
Great, thanks. I can reproduce the problem now.
