### ISSUE TITLE
simple: panic in LintSimplerReturn

### ISSUE THREAD

**Issue by iand** [dominikh/go-tools#96]
I'm using latest master (commit f637af825144df9db357bdbe921707f4a535f316). I am on Go tip, Linux but this also occurs with 1.8.1.

Here's the smallest reproducer I could get: 

```Go
package rhstats

import "time"

const DateFormat = "2006-01-02"

func parseTimeParams(from, to string) (fromTime, toTime time.Time, err error) {
	toTime, err = time.Parse(DateFormat, to)
	if err != nil {
		return fromTime, toTime, err
	}

	return fromTime, toTime, nil
}
```
Running gosimple with no args causes this panic:

```
panic: runtime error: index out of range

goroutine 248 [running]:
honnef.co/go/tools/simple.(*Checker).LintSimplerReturn.func1.1(0x8645c0, 0xc4200c8e70, 0xc420ee2601)
	/home/iand/src/honnef.co/go/tools/simple/lint.go:913 +0xcec
go/ast.inspector.Visit(0xc4230c0080, 0x8645c0, 0xc4200c8e70, 0x863cc0, 0xc4230c0080)
	/opt/go/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0x863cc0, 0xc4230c0080, 0x8645c0, 0xc4200c8e70)
	/opt/go/src/go/ast/walk.go:52 +0x66
go/ast.Walk(0x863cc0, 0xc4230c0080, 0x864a40, 0xc4200c8ea0)
	/opt/go/src/go/ast/walk.go:344 +0xdcb
go/ast.Inspect(0x864a40, 0xc4200c8ea0, 0xc4230c0080)
	/opt/go/src/go/ast/walk.go:385 +0x4b
honnef.co/go/tools/simple.(*Checker).LintSimplerReturn.func1(0x864a40, 0xc4200c8ea0, 0x865101)
	/home/iand/src/honnef.co/go/tools/simple/lint.go:928 +0xda
go/ast.inspector.Visit(0xc420a96000, 0x864a40, 0xc4200c8ea0, 0x863cc0, 0xc420a96000)
	/opt/go/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0x863cc0, 0xc420a96000, 0x864a40, 0xc4200c8ea0)
	/opt/go/src/go/ast/walk.go:52 +0x66
go/ast.walkDeclList(0x863cc0, 0xc420a96000, 0xc4200ca940, 0x3, 0x4)
	/opt/go/src/go/ast/walk.go:38 +0x95
go/ast.Walk(0x863cc0, 0xc420a96000, 0x8649c0, 0xc4200d8200)
	/opt/go/src/go/ast/walk.go:353 +0x255e
go/ast.Inspect(0x8649c0, 0xc4200d8200, 0xc420a96000)
	/opt/go/src/go/ast/walk.go:385 +0x4b
honnef.co/go/tools/simple.(*Checker).LintSimplerReturn(0xc4200c6190, 0xc421cf3110)
	/home/iand/src/honnef.co/go/tools/simple/lint.go:932 +0xd8
honnef.co/go/tools/simple.(*Checker).LintSimplerReturn-fm(0xc421cf3110)
	/home/iand/src/honnef.co/go/tools/simple/lint.go:46 +0x34
honnef.co/go/tools/lint.(*Linter).Lint.func1(0xc423ccfc40, 0xc421cf2d20, 0xc421cf3110)
	/home/iand/src/honnef.co/go/tools/lint/lint.go:253 +0x93
created by honnef.co/go/tools/lint.(*Linter).Lint
	/home/iand/src/honnef.co/go/tools/lint/lint.go:247 +0x1577
```

**Comment by mvdan** [comment]
Probably related to the func's return type, `(fromTime, toTime time.Time, err error)`, since it groups two under a single type.

Try rewriting into `(fromTime time.Time, toTime time.Time, err error)` and see if you still get the crash. That could help you get a much smaller reproducer.

**Comment by iand** [comment]
Yes, you're correct. Rewriting using `(fromTime time.Time, toTime time.Time, err error)` avoids the panic.
